### ISSUE TITLE
Include libmysqlclient-dev

### ISSUE THREAD

**Issue by mreider** [tiangolo/uwsgi-nginx-flask-docker#1]
Many / most applications need a database. Can you add these dependencies, or show how you would recommend we add them ourselves?

**Comment by gabeibarra** [comment]
In production apps, it's likely your db will be on another machine, but even when it's on the same machine it has its own start/stop/restart process independent of of the starting of your app server. So - it's easy to compare to having two docker services running -
1. This repo for your flask app + server
2. Another separate image for your db server.
The [MySQL dockerhub](https://hub.docker.com/_/mysql/) has pretty informative documentation on having your db container communicate with your app server container
I also found [this article](http://severalnines.com/blog/mysql-docker-containers-understanding-basics) helpful - mainly because (about halfway into the article), he describes a docker method for linking the two services. When restarting the service, it sometimes gets reassigned a new IP address, so linking helps keep your other running service in touch with the newly assigned address.

**Comment by tiangolo** [comment]
@mreider I first though that you needed to include the DB in the same container (I think @gabeibarra was thinking the same) but now I see that you really refer to the (driver) client libraries.

It is possible that the needs vary depending on the specific application that you are building, so it's better that each one installs the needed client libraries. For example, right now you need a MySQL client, but other application might need a PostgreSQL client, or even an ElasticSearch or Cassandra client driver.

---

In your case, interacting with MySQL from Python my suggestion is [PyMySQL](https://github.com/PyMySQL/PyMySQL).

So you would probably need to use a `Dockerfile` like:

```Dockerfile
FROM tiangolo/uwsgi-nginx-flask

RUN pip install --upgrade pip
RUN pip install PyMySQL

COPY ./app /app

WORKDIR /app/

EXPOSE 80
```

---

Now, as a personal suggestion, right now I'm using [Flask-SQLAlchemy](http://flask-sqlalchemy.pocoo.org/) and it works great with Flask (it's maintained by the same guys as Flask itself). 

In any case, If you use SQLAlchemy you would install the dependencies that you need (as required by SQLAlchemy) to support the DB back ends that you need.

In my case, using a PostgreSQL, this is how (a simplified version of) one of my `Dockerfile`s look like:

```Dockerfile
FROM tiangolo/uwsgi-nginx-flask

RUN pip install --upgrade pip
RUN pip install flask-sqlalchemy
RUN pip install psycopg2

COPY ./app /app

WORKDIR /app/

EXPOSE 80
```

Those `RUN pip install` take care of installing the dependencies.

---

Now, in your case, for MySQL with Flask-SQLAlchemy you would probably change `psycopg2` for `PyMySQL` (using the same pure driver suggested above):

```Dockerfile
FROM tiangolo/uwsgi-nginx-flask

RUN pip install --upgrade pip
RUN pip install flask-sqlalchemy
RUN pip install PyMySQL

COPY ./app /app

WORKDIR /app/

EXPOSE 80
```

**Comment by luckydonald** [comment]
Nice, I was wondering for a flask DB driver anyway.

**Comment by tiangolo** [comment]
I'll assume this issue is solved as there's been more than a month since it was created.

**Comment by luckydonald** [comment]
@gabeibarra I found it more practical to have the DBs running outside of docker, they are now on the host itself.
That way I won't accidentally delete their data volumes etc.

**Comment by tiangolo** [comment]
Just as advice, that's the point of Docker, you don't have to install, configure and run anything outside (and learn all the steps involved). And you don't have to deal with connections and security that much as you would with local installations as everything is linked by Docker.

Also, you can have several isolated DBs for each application stack, all on a single host.

If you are afraid of deleting your data, you should use data volumes (as recommended by Docker). All the main DB official images have instructions to do so.

For example, for the current latest MySQL, with would include:

* Create a named Docker volume:

```bash
docker volume create --name db-data
```

* Run the MySQL:

```bash
docker run --name some-mysql -e MYSQL_ROOT_PASSWORD=my-secret-pw -v db-data:/var/lib/mysql -d mysql:5.7
```

* And then start your container using that MySQL with something like:

```bash
docker run -d --name my-app --link some-mysql:db -p 80:80 my-app-image
```

---


If you are using Docker Compose, a `docker-compose.yml` file could be as simple as:

```yml
version: '2'
services:
  web:
    build: ./web
    ports:
    - '80:80'
  db:
    image: mysql:5.7
    environment:
      - 'MYSQL_ROOT_PASSWORD=my-secret-pw'
    volumes:
      - 'db-data:/var/lib/mysql'
volumes:
  db-data:
```
