### ISSUE TITLE
cant connect mongodb

### ISSUE THREAD

**Issue by habout632** [tiangolo/uwsgi-nginx-flask-docker#10]
why can,t connect mongodb 
eg:
data=source_client.users.users.find({"_id":ObjectId('5840e3eaf1d30043c60cae53')})[0]

feedback:
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>

**Comment by tiangolo** [comment]
Are you using a `docker-compose.yml` or something similar?

You need to somehow have your MongoDB container in the same network (or accessible from the network) of your Flask container.

One option is having a `docker-compose.yml`.

Other option is to start everything with `docker` commands, as in `docker run ..... --link mymongo:mongo .....`.

**Comment by tiangolo** [comment]
Are you still having issues? Should we close this issue?

**Comment by tiangolo** [comment]
As this conversation is getting old I will assume you solved your issues.
