### ISSUE TITLE
My Flask app accepts command line arguments

### ISSUE THREAD

**Issue by esdotzed** [tiangolo/uwsgi-nginx-flask-docker#100]
What is the best practice to pass those into the docker? Thanks!

**Comment by tiangolo** [comment]
The best way to pass configuration is as environment variables. Here's a [longer article about that at 12 factor apps](https://12factor.net/config).

For example:

* Create a file `config.py` with:

```Python
import os

ENVIRONMENT = os.getenv("ENVIRONMENT", default="production")
```

* A file `main.py` with:

```Python
from flask import Flask

from config import ENVIRONMENT

app = Flask(__name__)

@app.route("/")
def hello():
    return "Hello World from Flask in this environment: " + ENVIRONMENT

if __name__ == "__main__":
    # Only for debugging while developing
    app.run(host='0.0.0.0', debug=True, port=80)
```

* And a `Dockerfile`:

```Dockerfile
FROM tiangolo/uwsgi-nginx-flask:python3.7

COPY ./app /app
```

* Build your Docker image.

* And then run it, passing `ENVIRONMENT` as an environment variable, e.g.:

```bash
docker run -d -p 80:80 -e ENVIRONMENT=testing mysuperimage
```

**Note**: I'm not running all that in my machine, I'm just putting it here as I think of it, so it's quite probable that there's an error here or there. But I think you can get the idea from that.

**Comment by esdotzed** [comment]
Thanks for detailed response! I am currently using uwsgi options to pass those parameters, so I have to add some options to the uwsgi.ini file. I think your approach could be cleaner, no code changes needed at all if those parameter need to be updated. I might refactor my solution later.
Thanks!

**Comment by tiangolo** [comment]
Also, if you want to see all my "tricks", check out my full-stack project generatos :wink: 

With PostgreSQL: https://github.com/tiangolo/full-stack

and with NoSQL Couchbase: https://github.com/tiangolo/full-stack-flask-couchbase

**Comment by esdotzed** [comment]
so cool, thanks!
