### ISSUE TITLE
Celery workers

### ISSUE THREAD

**Issue by erikwestlund** [tiangolo/uwsgi-nginx-flask-docker#101]
I'm coming from PHP world where I'm quite comfortable. I've used docker in development for a while and this image has worked well.

I'm thinking down the line to when I go into production with the little app I'm developing. Python/Flask server admin is new to me, but I'm quite experienced with nginx/ubuntu/supervisor/etc.

I will probably run all my services (postgres, rabbitmq, redis) on a separate box or used managed services.  That seems like it should be straightforward to set up using standard config.

However, I'm wondering your advice on a celery worker.  I've got everything working  in dev.  

I figure in production I just need supervisor to run my celery workers.  I don't see any reason I would need a separate box (low traffic) and would probably want to just patch the current image to run the workers.  

If I add a file to /etc/supervisor/conf.d with all the correct configuration in my Dockerfile, and then run:

supervisorctl reread
supervisorctl update
supervisorctl start celery-worker:*

In the Dockerfile, do you see a reason taht wouldn't work?

**Comment by tiangolo** [comment]
I suggest you put your Celery worker in a different container. And Postgres, RabbitMQ and Redis on separated containers too.

---

I normally manage everything with Docker. I use Docker Compose for local development and Docker Swarm mode, which is the system included with Docker to deploy to a cluster of Docker servers. It's quite easy to set up and use if you are already familiar with Docker and Docker Compose.

For a situation like yours, I would start the project with this generator: https://github.com/tiangolo/full-stack

It includes Flask in one container, Postgres in another, Celery workers that use the same SQLAlchemy models in another, RabbitMQ in another.

You can start a cluster quite easily with Docker Swarm and put a main Traefik proxy / Load Balancer (like a main Nginx or HAproxy if you have heard of that), and it can handle automatic generation and renewal of HTTPS certificates with Let's Encrypt. With that, you can have one or more stacks with multiple domains all with HTTPS, even on a single machine.

To set the cluster up that way, here's the guide: https://medium.com/@tiangolo/docker-swarm-mode-and-traefik-for-a-https-cluster-20328dba6232

Anyway, I think you can use the generator to create a simple project (it's just a couple commands to run it) and then check, compare and copy whatever you see that works for you.

**Comment by tiangolo** [comment]
I'll assume you were able to solve your problem, so I'll close this issue now.

But feel free to re-open it, add more comments or create new issues.
