### ISSUE TITLE
flask-socketio integration

### ISSUE THREAD

**Issue by mcelisr1** [tiangolo/uwsgi-nginx-flask-docker#102]
Hi,
Is there any way to configure the image to be compatible with flask-socketio (web-sockets), through uWSGI or nginx?
This suggests the flask-socketio documentation
https://flask-socketio.readthedocs.io/en/latest/#uwsgi-web-server

**Comment by tiangolo** [comment]
That's a good question. It's not as simple as installing a package or configuring something.

Check more info in this comment: https://github.com/tiangolo/uwsgi-nginx-flask-docker/issues/85#issuecomment-425446266

**Comment by mcelisr1** [comment]
HI @tiangolo 

I was trying to achieve my goal by customizing the files: uwsgi.ini and custom.conf (nginx) as follows:
`uwsgi.ini`
```
[uwsgi]
module = app.main
callable = app
gevent = 1000
http-websockets = true
master = true
```

`custom.conf`
```
server {    
    location /socket.io {
        include uwsgi_params;
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_pass http://127.0.0.1/socket.io;
    }
}
```

I felt excited because I managed to get my clients to connect to the websocket, but the flow does not work at all. I'm just saying this to show you that I was reviewing the issue and I was close to making it work.

However, checking your recommendation in: #85 ...  I understand that it is a very cumbersome topic, so I will perform a microservice to work with websockets that will not use your great images.

Thank you so much for everything!
