### ISSUE TITLE
Request: serve from static dir to root if file found

### ISSUE THREAD

**Issue by benyanke** [tiangolo/uwsgi-nginx-flask-docker#104]
It would be great to generalize the static dir functionality to work with any app - an app I am using this for is already written, so is less flexible.

It would be awesome to have an additional env which could allow any web request to the root to first check the static dir for file existence, then go to the app.

For example, static contains img1.jpg, and style.css.

Requests for /random and /test would go to the app, but /img1.jpg and /style.css would go to the static files because they exist.

**Comment by tiangolo** [comment]
You can achieve that with the snippet in [Quickstart for SPAs section](https://github.com/tiangolo/uwsgi-nginx-flask-docker#quickstart-for-spas)

It does exactly that.

```Python
# Everything not declared before (not a Flask route / API endpoint)...
@app.route('/<path:path>')
def route_frontend(path):
    # ...could be a static file needed by the front end that
    # doesn't use the `static` path (like in `<script src="bundle.js">`)
    file_path = os.path.join(app.static_folder, path)
    if os.path.isfile(file_path):
        return send_file(file_path)
    # ...or should be handled by the SPA's "router" in front end
    else:
        index_path = os.path.join(app.static_folder, 'index.html')
        return send_file(index_path)
```

I think that doing it outside of Flask wouldn't be a lot more error-prone and dangerous.

**Comment by benyanke** [comment]
Thanks! I will try this.

**Comment by tiangolo** [comment]
I assume you were able to solve your problem, so I'll close this issue now.

But feel free to re-open it, add more comments or create new issues.
