### ISSUE TITLE
Passing arguments to main.py

### ISSUE THREAD

**Issue by arashsa** [tiangolo/uwsgi-nginx-flask-docker#11]
I'm trying to understand how the main.py file in the /app folder is called, and how I can send arguments to it? I have a project where I would like to start the main.py file by passing it an argument when I create a container.

**Comment by tiangolo** [comment]
The most "Docker" way, also the most straightforward and probably the most "Pythonic" way too would be with environment variables.

Don't run `python main.py` unless you are currently developing. But in production, let the image take care of running it all with Supervisor.

To read environment variables from your `main.py` you would use [`os.environ`](https://docs.python.org/2/library/os.html#os.environ). It would look something like:

```python
import os
my_var = os.environ.get('ENV_VAR_FROM_OUTSIDE', 'some default value')
```

And then run your Docker container with something like:

```bash
docker run -d -e ENV_VAR_FROM_OUTSIDE="an-external-value" my-image
```

Or if you are using `docker-compose`, your `docker-compose.yml` file would look something like:

```yaml
version: '2'
services:
  web:
    build: ./
    environment:
      - ENV_VAR_FROM_OUTSIDE="an-external-value"
```

Double check anything I wrote above before copy-pasting, as I'm not writing it in an editor nor testing the code in this answer, there could be syntax errors.

**Comment by tiangolo** [comment]
Are you still having issues? Should we close this issue?

**Comment by tiangolo** [comment]
As this conversation is getting old I will assume you solved your issues.
