### ISSUE TITLE
best approach to include custom supervisord.conf ?

### ISSUE THREAD

**Issue by AYEG** [tiangolo/uwsgi-nginx-flask-docker#111]
Hello,
I've used this configured image before for a small project and it worked like a charm! 
 
For a new project I'd like to include custom configuration for supervisord, looking through the baseimage dockerfile (
https://hub.docker.com/r/tiangolo/uwsgi-nginx) /,I found:
# Custom Supervisord config
> COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

I've tried building my own baseimages last time, but this takes up a lot of time for every config change. 

If I leave the baseimage as it is, but instead include a custom COPY supervisord.conf to that location ( /etc/supervisor/conf.d/supervisord.conf) in the final dockerfile.  

Would this be a valid approach?
Thank you

**Comment by AYEG** [comment]
Oh wow I didn't even see that project before, that on a whole different level for me, but certainly interesting,  I would like to reach this level of automation at some point, I like what you did with the step by step input variables. 

Right now I need a bunch of RQ workers for a react (test) app,  not expecting a high load right at all. I've found running traefik a good experience and will need to run a db and redis alongside it. 

Looking at the features in the full-stack project ,I'm still learning as I go along and there's quite a few things that i'm not currently using (or haven't even thought about yet), like Api-spec, pytest, marshmallow, webargs, testing, jwt, I'm just using sqllite and simple cookie based authentication.

**Comment by tiangolo** [comment]
Don't worry, you don't need to use all those features, those are just to simplify building JSON APIs. But you can generate a project and copy the parts that you need and remove all the rest.

---

For your case:

You can build and serve your React frontend in an isolated container using the technique from that project. It can coexist under the same domain as your Flask app by separating them both by path with Traefik. And if you have already used Traefik, it's going to be quite easy for you.

And you can re-use many of the `docker-compose.*.yml` files.

That project uses Celery as the equivalent of RQ and RabbitMQ as the equivalent of Redis. But as it is all Docker-based, you can switch everything very easily. 

Change the docker-composes from RabbitMQ to Redis.

In the file `worker.py` you could put your RQ stuff, and probably replace the `celeryworker` service with your RQ service.

If you are using a DB like PostgreSQL, MySQL, MongoDB, etc, you can put it in a separate container too.

If you plan on using Couchbase as a DB, I have a dediciated project generator for that: https://github.com/tiangolo/full-stack-flask-couchbase

Don't be afraid of adding other containers to do separate tasks. I would say it's orders of magnitude easier with Docker as you can set it up with environment variables and everything is already configured, finetuned and secured.

**Comment by AYEG** [comment]
Thank you I will try this out. Appreciate the effort you put into explaining the required changes

**Comment by AYEG** [comment]
Hello!
I converted my project flask files into the full stack structure and includes the env variables on the react frontend. Looking forward to testing it out and configuring rq dashboard/workers.

Right now I'm stuck trying to fix this CORS issue. I've pushed the app folder to my pc via local lan and succesfully build and run all the images. when I navigate from my mac to the ip of the other machine to access the pages it shows me e.g.

> /Swagger/ is giving me  The URL origin (http://localhost) does not match the page (http://192.168.99.123) error

The frontend console is printing:

> 1.eddfca95.chunk.js:1 GET http://localhost/users/me net::ERR_CONNECTION_REFUSED
> 
> (anonymous) @ main.5c63ca03.chunk.js:1
> main.5c63ca03.chunk.js:1 Error: Network Error
>     at e.exports (1.eddfca95.chunk.js:1)
>     at XMLHttpRequest.p.onerror (1.eddfca95.chunk.js:1)

I've tried changing the localhost in etc/host to on the other pc  to 192.168.99.123. Also checked all my the CORS domains listed in env.backend.

What am I missing here?

**Comment by AYEG** [comment]
Ok,  I figured it out :), for anyone else going down this road with a remote machine: you probably just need to put the remote machine address in the env files for backend and frontend where it now says localhost

**Comment by tiangolo** [comment]
Sorry for the delay! I was busy building [**FastAPI**](https://github.com/tiangolo/fastapi).

I'm glad you solved it!

In any case, the specific changes needed are:

* Set your frontend to communicate with the backend at http://192.168.99.123, if you are using the env vars, do it there. If you have some other config JS file, then there.
* In your backend, add the "origin" where your frontend is being accessed to the CORS list of origins env var. 
    * So, if your frontend is at http://192.168.99.123, add that to the CORS env var.
    * If your backend is at http://192.168.99.123 and your frontend is running locally with Vue CLI (for example), add http://localhost:8080 (the URL for your frontend in Vue CLI).
