### ISSUE TITLE
502 Bad Gateway when serving static HTML

### ISSUE THREAD

**Issue by raezazel** [tiangolo/uwsgi-nginx-flask-docker#114]
Hi! Thanks a lot for the docker template! I'm just having an issue with serving a static HTML file while using uwsgi and nginx. I get a 502 Bad Gateway error.

My file-tree looks like this

```
├── Dockerfile
├── app
│  ├── app
│  │   ├── main.py
│  │   └── static
│  │       └── index.html
│  └── uwsgi.ini
└── requirements.txt
```

My main.py contains the following code:
```
app = Flask(__name__)
@app.route("/")
def serve():
     html_path = os.path.join(app.static_folder, 'index.html')
     return send_file(html_path)
```

I tried adding the following to my uwsgi.ini, but this also didn't help
```
static-index = index.html
static-map = /static/=%d/app/static/
```

Hopefully you have some insight as to what's going wrong here. Thank you :)

**Comment by raezazel** [comment]
I'm an idiot. I left an old import for a module that's not in my requirements.txt.....

**Comment by tiangolo** [comment]
Sorry for the delay! I was busy building [**FastAPI**](https://github.com/tiangolo/fastapi).

> I'm an idiot. I left an old [...]

Hehe, don't worry. That's just the most used phrase by any professional developer. The good thing is, it always comes right after finding a bug. :tada:  :bug: 

I'm glad you solved your issue.
