### ISSUE TITLE
python2.7-alpine3.8 build failed

### ISSUE THREAD

**Issue by danpatdav** [tiangolo/uwsgi-nginx-flask-docker#115]
Looks like the python2.7-alpine3.8 build failed for some reason and did not make it to dockerhub.

**Comment by tiangolo** [comment]
Sorry for the delay! I was busy building [**FastAPI**](https://github.com/tiangolo/fastapi).

I recently added Travis to the whole system, so now images should be built and pushed faster and I get notifications when anything goes wrong.

All the supported images are available in Docker Hub now :smile:

**Comment by tiangolo** [comment]
I guess you were able to use the new image built with Travis CI. So I'll close this issue now.

But feel free to re-open it, add more comments or create new issues.
