### ISSUE TITLE
Running project with nested app directories (create_app())

### ISSUE THREAD

**Issue by IDmedia** [tiangolo/uwsgi-nginx-flask-docker#118]
Hi, I'm following Miguel Grinberg's Flask book and trying to host his example using this image:
https://github.com/miguelgrinberg/oreilly-flask-apis-video/tree/master/orders

I have no issues hosting my own "single file" flask examples, but in this case he creates the app variable in create_app()/__init__.py. Is there any special trick to how to get it to work in uwsgi? To my understanding I have to create the app instance outside the __main__ function. Any suggestions how I may rewrite this example without "breaking" the ease of testing it locally by just issuing python run.py?

Copying everything inside the __main__ function outside the function seems to do the trick, but I wonder if there's a better way around this. Additionally, I'm having issues to serve static files since the project is nested in two app directories. The first app dir contains run.py and another dir called app (which holds the static dir) while the image is looking for the static directory one level up (the same as run.py).

Any suggestions on how to solve this in a good way are highly appreciated.
I'm still new to flask so sorry if this is a stupid question or a silly way to structure a project. :)

**Comment by tiangolo** [comment]
I haven't seen his book or videos, but giving a quick look at the example code, it seems you could create a file `main.py` living beside `run.py` with:

```Python
import os
from app import create_app, db

app = create_app(os.environ.get('FLASK_CONFIG', 'production'))
```

That way there would be a variable `app` inside of the file `main.py` with the actual Flask app and uwsgi would be able to use it.

You could also create a file `my_custom_prestart_script.py` with something like:

```Python
import os
from app import create_app, db
from app.models import User

if __name__ == '__main__':
    app = create_app(os.environ.get('FLASK_CONFIG', 'development'))
    with app.app_context():
        db.create_all()
        # create a development user
        if User.query.get(1) is None:
            u = User(username='john')
            u.set_password('cat')
            db.session.add(u)
            db.session.commit()
```

And then create a file in `/app/prestart.sh` with:

```bash
#! /usr/bin/env bash

# Run custom Python script before starting
python /app/my_custom_prestart_script.py
```

That would run the initialization of the app (create the DB tables, etc) before starting the server.

Check the docs: https://github.com/tiangolo/uwsgi-nginx-flask-docker#custom-appprestartsh

Depending on how you structure your code, you might have to modify the local `uwsgi.ini` file, with something like:

```ini
[uwsgi]
module = app.main
callable = app
```

Check the docs: https://github.com/tiangolo/uwsgi-nginx-flask-docker#quick-start-for-bigger-projects-structured-as-a-python-package

About the location of the static files, check the docs: https://github.com/tiangolo/uwsgi-nginx-flask-docker#custom-static-path

---

Now, an alternative suggestion, I created a full-stack project generator to build APIs with Flask using several plug-ins to simplify several parts of the process: https://github.com/tiangolo/full-stack

It might be useful and more or less similar to what I think you are probably wanting to do. It's already integrated with Docker, including a database in another Docker container, simple local development, etc.

That would be a possible next step in your path.

---

Now, just as an idea:

After building APIs in Python with several teams, for several years, I ended up building something to integrate the best ideas I found from several projects, frameworks, etc, and created FastAPI.

It's a framework for building APIs, with very high performance (about 800% of what you can get with Flask and this image). 

It's made to have autocompletion everywhere, to be very intuitive, and to reduce the amount of code you have to write to a half or even less.

And the documentation / tutorial is designed for everyone with basic notions of Python and web.

If you are building APIs with Python, you might want to give it a look (give it 10 minutes and you'll know if you like it or not right away): https://github.com/tiangolo/fastapi

Also, I'm about to create a project generator (equivalent to the one mentioned above) based on FastAPI, that might be useful too.

**Comment by IDmedia** [comment]
Thank you so much for your time and in-depth reply! I'll give it a try. I'll most definitely look into fastapi. In fact, it seems to solve a lot of the things I've been struggling with lately. Great work!

**Comment by tiangolo** [comment]
Awesome! :tada:
