### ISSUE TITLE
cannot handle images in the html

### ISSUE THREAD

**Issue by huzhyi21** [tiangolo/uwsgi-nginx-flask-docker#125]
In my ubuntu server, I try to deploy flask app based on this docker image. However, it doesn't work with images in the html.
(1) directory structure
I have a directory structure like example-flask-package-python3.7.zip:
.
├── app
│   ├── app
│   │   ├── main1.py
│   │   ├── main.py
│   │   ├── model
│   │   ├── static
│   │   │   └── images
│   │   │           ├── logo_python2.jpg
│   │   │           └── logo_python.png
│   │   ├── templates
│   │   │   ├── hi.html
│   │   │   └── upload.html
│   │   └── upload
│   └── uwsgi.ini
├── Dockerfile

(2) main.py
`
from flask import Flask,render_template, request, url_for, send_from_directory,jsonify, redirect
app = Flask(__name__)

@app.route("/")
def hello():
	return render_template('hi.html')
if __name__ == "__main__":
    app.run(host='0.0.0.0', debug=True, port=80)
`
(3) hi.html
In the hi.thml, in addition to html, head, body, I simplily insert two images. the code to give the src of images are as follows:

 src="./static/images/logo_python.png"
src="{{url_for('static',filename='images/logo_python2.jpg')}}"

The images are shown in my pc, but it doesn't work when I deployed the app in the remote ubuntu server. It looks like the web server cannot find the two images.

Please anyone can help me to solve it? Thanks in advance.

**Comment by tiangolo** [comment]
> The images are shown in my pc [...]

Here do you refer by running the `flask` command or in Docker?

Where does your image URL point to in the rendered HTML in your deployed server?
