### ISSUE TITLE
processes = 1 still launch 2 processes

### ISSUE THREAD

**Issue by rockkoca** [tiangolo/uwsgi-nginx-flask-docker#126]
Hi,

How to launch only 1 process? I used processes = 1 in uwsgi config file and ENV UWSGI_PROCESSES 1 in docker file. It seems no one helps. It always launch 2 processes.

Thanks,

**Comment by rockkoca** [comment]
using meinheld-gunicorn-flask-docker instead

**Comment by tiangolo** [comment]
It normally launches 2 processes because one is the "master" that spawns the second process.
