### ISSUE TITLE
POST file problem

### ISSUE THREAD

**Issue by sypho8** [tiangolo/uwsgi-nginx-flask-docker#128]
Hi,

I'm trying to include a file in the POST request to the flask application and it fails.

Using docker logs, that's the output:

`2019/03/27 11:33:19 [warn] 11#11: *1 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000001, client: 172.17.0.1, server: , request: "POST /predict HTTP/1.1", host: "localhost"`
`2019/03/27 11:34:19 [error] 11#11: *1 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.17.0.1, server: , request: "POST /predict HTTP/1.1", upstream: "uwsgi://unix:///tmp/uwsgi.sock", host: "localhost"`

**Comment by tiangolo** [comment]
The `upstream timed out` means that Nginx is saying that uWSGI didn't respond on time.

That normally means that your Flask code took too long to respond, maybe you are processing the file live before returning the response or something similar.

You can use the option to customize Nginx: https://github.com/tiangolo/uwsgi-nginx-flask-docker#customizing-nginx-additional-configurations

And use for example: http://nginx.org/en/docs/http/ngx_http_uwsgi_module.html#uwsgi_read_timeout

**Comment by ong3ri** [comment]
I don't get the timeout issue, instead uWSGI gets a segfault then restarts. I've tried everything, nothing works

`backend_1       | 172.19.0.1 - - [16/Apr/2019:08:03:28 +0000] "OPTIONS /api/galleries/94e8072d63bf4d31be79814c784c676a/images HTTP/1.1" 200 0 "http://localhost:1002/galleries/94e8072d63bf4d31be79814c784c676a/images" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36" "-"
backend_1       | [pid: 39|app: 0|req: 12/15] 172.19.0.1 () {48 vars in 886 bytes} [Tue Apr 16 08:03:28 2019] OPTIONS /api/galleries/94e8072d63bf4d31be79814c784c676a/images => generated 0 bytes in 9 msecs (HTTP/1.1 200) 7 headers in 292 bytes (0 switches on core 0)
backend_1       | 2019/04/16 08:03:28 [warn] 16#16: *25 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000009, client: 172.19.0.1, server: , request: "POST /api/galleries/94e8072d63bf4d31be79814c784c676a/images HTTP/1.1", host: "localhost:2001", referrer: "http://localhost:1002/galleries/94e8072d63bf4d31be79814c784c676a/images"
backend_1       | !!! uWSGI process 39 got Segmentation Fault !!!
backend_1       | 172.19.0.1 - - [16/Apr/2019:08:03:29 +0000] "POST /api/galleries/94e8072d63bf4d31be79814c784c676a/images HTTP/1.1" 502 575 "http://localhost:1002/galleries/94e8072d63bf4d31be79814c784c676a/images" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36" "-"
backend_1       | 2019/04/16 08:03:29 [error] 16#16: *25 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 172.19.0.1, server: , request: "POST /api/galleries/94e8072d63bf4d31be79814c784c676a/images HTTP/1.1", upstream: "uwsgi://unix:///tmp/uwsgi.sock:", host: "localhost:2001", referrer: "http://localhost:1002/galleries/94e8072d63bf4d31be79814c784c676a/images"
backend_1       | DAMN ! worker 2 (pid: 39) died :( trying respawn ...
backend_1       | Respawned uWSGI worker 2 (new pid: 41)
`

**Comment by eamanu** [comment]
Hi @sypho8  this issue is related to https://github.com/tiangolo/uwsgi-nginx-flask-docker/issues/39

I solve this problem using a mysetting.conf file:

```
uwsgi_read_timeout 600s;
```

On the Dockerfile I write: `COPY mysetting.conf /etc/nginx/conf.d/`

And the problem was solved.

**Comment by tiangolo** [comment]
Thanks for the report @eamanu !
