### ISSUE TITLE
base image update can break dependent ones

### ISSUE THREAD

**Issue by tramora** [tiangolo/uwsgi-nginx-flask-docker#129]
Thanks for your base image @tiangolo I find it useful. 
However I had to build my own starting from your tiangolo/uwsgi-nginx-flask:python3.6-alpine3.8.

I had to tweak a little bit the nginx file (for SSL purpose) and overwrite your **entrypoint.sh**

```bash
#! /usr/bin/env sh
set -e

/uwsgi-nginx-entrypoint.sh

# Explicitly add installed Python packages and uWSGI Python packages to PYTHONPATH
# Otherwise uWSGI can't import Flask
export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python3.6/site-packages:/usr/lib/python3.6/site-packages

cp /app/nginx-server.conf /etc/nginx/conf.d/nginx-server.conf

exec "$@"
```

My tweaks are quite dependent of your base image internals and when you change your base image without changing the tag (python3.6-alpine3.8) it can break mine. You must have considered the global image functionality has not changed and python and alpine version have not changed either. 

Do you have a better idea to manage this issue ?

**Comment by tiangolo** [comment]
> Thanks for your base image @tiangolo I find it useful.

I'm glad to hear that.

---

I guess you are using your own `Dockerfile` based on this image, right?

You can override completely all the logic to generate the `nginx.conf` and provide your own directly, with all your custom SSL configurations: https://github.com/tiangolo/uwsgi-nginx-flask-docker#overriding-nginx-configuration-completely

That way you don't have to overwrite the default entrypoint.

Does that solve your problem?

**Comment by tramora** [comment]
I've seen this section @tiangolo but my initial need was to customize only the nginx virtual host in /etc/nginx/conf.d/ (not the default /etc/nginx/nginx.conf).

My override of entrypoint.sh was fine but it broke 2 months ago when you updated the image internals.

My concern is to avoid future issues if you update this base image with the same tag.
Yes indeed as you suggested, customizing the whole /etc/nginx/nginx.conf may be a solution (even if it forces me to put there the server {} section too)

Thank you, I guess we can close the issue

**Comment by tiangolo** [comment]
Cool, thanks for reporting back.
