### ISSUE TITLE
How to configure wildcard subdomains?

### ISSUE THREAD

**Issue by alltheoptions** [tiangolo/uwsgi-nginx-flask-docker#13]
How can i configure wildcard subdomains using this image?

**Comment by tiangolo** [comment]
Were you able to solve it @alltheoptions ?

**Comment by alltheoptions** [comment]
Yes, the issue was in flask config,
With this:
`if __name__ == "__main__":
    app.run(host='0.0.0.0', debug=False, port=80)`

I had to remove port from SERVER_NAME so instead of:
`SERVER_NAME = 'domain.eu:80'`
correct is:
`SERVER_NAME = 'domain.eu`

And overwriten nginx.conf, but i dont know if this is nessecary:

`server {

    location / {
        try_files $uri @app;
    }
    location @app {
        include uwsgi_params;
        uwsgi_pass unix:///tmp/uwsgi.sock;
    }
    location /static {
        alias /app/static;
    }
}

server {
    listen      80;
    server_name *.domain.eu;

     #Rewrite all nonssl requests to ssl.
     #return 301 https://$host$request_uri;

    location / {
        try_files $uri @app;
    }
    location @app {
        include uwsgi_params;
        uwsgi_pass unix:///tmp/uwsgi.sock;
    }
    location /static {
        alias /app/static;
    }
}`

**Comment by tiangolo** [comment]
Cool! I'm glad it works now.

You shouldn't have to override `nginx.conf`.

---

There were a lot of changes recently, you can check the improvements, features, and changes here: https://github.com/tiangolo/uwsgi-nginx-flask-docker/releases/tag/v0.3.0
