### ISSUE TITLE
start.sh: 9: start.sh: source: not found

### ISSUE THREAD

**Issue by Nicersmeng** [tiangolo/uwsgi-nginx-flask-docker#130]
We build a docker image base on yours 2.7 version,we have modified prestart.sh as the doc said ,but the image cannot work,
1.when we enter image, exec ". start.sh", It can work well
2,exec "sh start.sh" It remind us source doesn`t exist,but we have use "RUN apt-get install linux-source" 
3. modify the start.sh is another to run the service ,change source to "./".BUT we dont know how to modify start.sh
could you please give me some help,Thank you

**Comment by tiangolo** [comment]
I'm not sure I understand the problem, but I think it might be that at some point you are trying to run:

```sh
sh start.sh
```

But you are probably already inside the directory `/app`. And the file `start.sh` is at `/`.

You can instead run:

```sh
sh /start.sh
```

Notice the extra `/`.
