### ISSUE TITLE
how to run other script after set up the server?

### ISSUE THREAD

**Issue by shmilyoyo** [tiangolo/uwsgi-nginx-flask-docker#131]
Thanks to the pre_start.sh, we can run other scripts before the server set up. But how could I run other scripts after the server set up. I tried to add some commands after the `exec /usr/bin/supervisord`, however, the following commands did not run.

**Comment by tiangolo** [comment]
Do you need to run something that has to be in the same memory of the the server?

Would it work running it on a separate Celery worker?

**Comment by shmilyoyo** [comment]
It is not necessary, but I put all the codes in one docker file. I want to run the model which fetch the data from the set up server. I realize that I could put the model in another docker file. 

Thanks for your help.

**Comment by tiangolo** [comment]
Cool! Thanks for reporting back.
