### ISSUE TITLE
Flask-ask using Python 3.7 image

### ISSUE THREAD

**Issue by IDmedia** [tiangolo/uwsgi-nginx-flask-docker#133]
I have multiple containers running that use the fantastic Python 2.7 image. I'm currently trying to migrate most of my scripts to Python 3, but I run into issues using Flask-Ask with the Python 3.7 image.

I have created a `main.py` with this example code: https://github.com/johnwheeler/flask-ask
I have then added `RUN pip install flask-ask` to the Dockerfile in order to install the required flask-ask module. However, with the Python 3 image I get the following error:

> Step 3/3 : RUN pip3 install flask-ask
>  ---> Running in e93140855c23
> Collecting flask-ask
>   Downloading https://files.pythonhosted.org/packages/6a/f5/d4709ae94584a0b1541e9b52b2d25a8a1bdb6e2da9d6870f23fdd0523a30/Flask-Ask-0.9.8.tar.gz (40kB)
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-install-yi9xpnhg/flask-ask/setup.py", line 8, in <module>
>         from pip.req import parse_requirements
>     ModuleNotFoundError: No module named 'pip.req'
> 

Some people recommend to downgrade pip to 9.0.3, but then I get a whole bunch of gcc errors.

**Comment by IDmedia** [comment]
Seems to be a bug in flask-ask. Work when using v.0.8.8:
`RUN pip install git+https://github.com/johnwheeler/flask-ask.git@v0.8.8`

**Comment by tiangolo** [comment]
I'm glad you solved it. Thanks for reporting back and closing the issue.
