### ISSUE TITLE
bind() failed

### ISSUE THREAD

**Issue by Askill** [tiangolo/uwsgi-nginx-flask-docker#136]
Hey, I am getting the following error:
2019/05/15 13:06:19 [emerg] 34#34: bind() to 0.0.0.0:80 failed (98: Address already in use)

I changed the config to support ssl, could this be the reason?

**Comment by tiangolo** [comment]
If you get that error in your local machine while running a `docker` command, that means that you already have something running at port `80`. It might be a previous container or something else.

You can check by opening a browser at `http://127.0.0.1`.

If the error is inside your Docker container, that means that you might have an already started container and are trying to run another command (another server) inside of the same container.

**Comment by Aponace** [comment]
Hey, I have the same issue when I didn't have it before with the same Dockerfile. I'm using tiangolo/uwsgi-nginx-flask:python2.7 as the base image.

I've changed in the past entrypoint.sh (to include custom nginx.conf):

`#! /usr/bin/env bash
set -e
# Get the maximum upload file size for Nginx, default to 0: unlimited
USE_NGINX_MAX_UPLOAD=${NGINX_MAX_UPLOAD:-0}
# Generate Nginx config for maximum upload file size
echo "client_max_body_size $USE_NGINX_MAX_UPLOAD;" > /etc/nginx/conf.d/upload.conf

# Get the number of workers for Nginx, default to 1
USE_NGINX_WORKER_PROCESSES=${NGINX_WORKER_PROCESSES:-1}
# Modify the number of worker processes in Nginx config
sed -i "/worker_processes\s/c\worker_processes ${USE_NGINX_WORKER_PROCESSES};" /etc/nginx/nginx.conf

# Set the max number of connections per worker for Nginx, if requested
# Cannot exceed worker_rlimit_nofile, see NGINX_WORKER_OPEN_FILES below
if [[ -v NGINX_WORKER_CONNECTIONS ]] ; then
    sed -i "/worker_connections\s/c\    worker_connections ${NGINX_WORKER_CONNECTIONS};" /etc/nginx/nginx.conf
fi

# Set the max number of open file descriptors for Nginx workers, if requested
if [[ -v NGINX_WORKER_OPEN_FILES ]] ; then
    echo "worker_rlimit_nofile ${NGINX_WORKER_OPEN_FILES};" >> /etc/nginx/nginx.conf
fi

# Get the URL for static files from the environment variable
#USE_STATIC_URL=${STATIC_URL:-'/app/website/public'}
# Get the absolute path of the static files from the environment variable
USE_STATIC_PATH=${STATIC_PATH:-'/app/website/public/'}
# Get the listen port for Nginx, default to 80
USE_LISTEN_PORT=${LISTEN_PORT:-80}

# Generate Nginx config first part using the environment variables
echo "server {
    listen ${USE_LISTEN_PORT};
    location / {
        root /app/website/public/;
        try_files \$uri  @app;
    }
    location @app {
        include uwsgi_params;
        uwsgi_pass unix:///tmp/uwsgi.sock;
    }" > /etc/nginx/conf.d/nginx.conf

# If STATIC_INDEX is 1, serve / with /static/index.html directly (or the static URL configured)
#if [[ $STATIC_INDEX == 1 ]] ; then
#echo "    location = / {
#        index $USE_STATIC_URL/index.html;
#    }" >> /etc/nginx/conf.d/nginx.conf
#fi

# Finish the Nginx config file
echo "}" >> /etc/nginx/conf.d/nginx.conf

exec "$@"
`
Nginx still serves pages as expected with uwsgi but there is another Nginx process trying to start. When doing `service nginx stop` inside the container it stops the running one a start a new one (the one it fails to start) with the same configuration.

**Comment by tiangolo** [comment]
@Aponace which command is showing you errors? How are you starting your container?

If you start it with: 

```bash
docker run -d --name mycontainer -p 80:80 myimage
```

Do you have errors? Where do you see the error? In the logs? The browser?

**Comment by Aponace** [comment]
My docker run command is:

```
docker run -d --name mycontainer -p 80:80 myimage
```

I see the error when I run `docker logs mycontainer`:

```
...

2019-05-21 15:05:09,827 INFO spawned: 'nginx' with pid 73
2019/05/21 15:05:09 [emerg] 73#73: bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
2019/05/21 15:05:09 [emerg] 73#73: bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
2019/05/21 15:05:09 [emerg] 73#73: bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
2019-05-21 15:05:10,857 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019/05/21 15:05:09 [emerg] 73#73: bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
2019/05/21 15:05:09 [emerg] 73#73: bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
2019/05/21 15:05:09 [emerg] 73#73: still could not bind()
nginx: [emerg] still could not bind()
2019-05-21 15:05:12,357 INFO exited: nginx (exit status 1; not expected)

...
```

Dockerfile:

```
FROM tiangolo/uwsgi-nginx-flask:python2.7

# Copy project files (different module + static path)
COPY /project/mycustomapp.py /app/mycustomapp.py
COPY /project/website/public /app/website/public

# copy CUSTOM UWSGI and ENTRYPOINT
COPY /project/uwsgi.ini /app
COPY /project/entrypoint.sh /entrypoint.sh

# Give access to nginx for static files
RUN chown -R nginx:nginx /app/website/public
RUN find /app/website/public -type d -exec chmod 755 {} +
RUN find /app/website/public -type f -exec chmod 644 {} +

# Give execute permission on custom entrypoint
RUN chmod +x /entrypoint.sh

# Clean original container default files (using different module)
RUN rm -rf main.py
```

uwsgi.ini
```
[uwsgi]
module = mycustomapp
callable = app
enable-threads = true
buffer-size = 8192
```
entrypoint.sh
```
#! /usr/bin/env bash
set -e
# Get the maximum upload file size for Nginx, default to 0: unlimited
USE_NGINX_MAX_UPLOAD=${NGINX_MAX_UPLOAD:-0}
# Generate Nginx config for maximum upload file size
echo "client_max_body_size $USE_NGINX_MAX_UPLOAD;" > /etc/nginx/conf.d/upload.conf

# Get the number of workers for Nginx, default to 1
USE_NGINX_WORKER_PROCESSES=${NGINX_WORKER_PROCESSES:-1}
# Modify the number of worker processes in Nginx config
sed -i "/worker_processes\s/c\worker_processes ${USE_NGINX_WORKER_PROCESSES};" /etc/nginx/nginx.conf

# Set the max number of connections per worker for Nginx, if requested
# Cannot exceed worker_rlimit_nofile, see NGINX_WORKER_OPEN_FILES below
if [[ -v NGINX_WORKER_CONNECTIONS ]] ; then
    sed -i "/worker_connections\s/c\    worker_connections ${NGINX_WORKER_CONNECTIONS};" /etc/nginx/nginx.conf
fi

# Set the max number of open file descriptors for Nginx workers, if requested
if [[ -v NGINX_WORKER_OPEN_FILES ]] ; then
    echo "worker_rlimit_nofile ${NGINX_WORKER_OPEN_FILES};" >> /etc/nginx/nginx.conf
fi

# Get the URL for static files from the environment variable
#USE_STATIC_URL=${STATIC_URL:-'/app/website/public'}
# Get the absolute path of the static files from the environment variable
USE_STATIC_PATH=${STATIC_PATH:-'/app/website/public/'}
# Get the listen port for Nginx, default to 80
USE_LISTEN_PORT=${LISTEN_PORT:-80}

# Generate Nginx config first part using the environment variables
echo "server {
    listen ${USE_LISTEN_PORT};
    location / {
        root /app/website/public/;
        try_files \$uri  @app;
    }
    location @app {
        include uwsgi_params;
        uwsgi_pass unix:///tmp/uwsgi.sock;
    }" > /etc/nginx/conf.d/nginx.conf

# If STATIC_INDEX is 1, serve / with /static/index.html directly (or the static URL configured)
#if [[ $STATIC_INDEX == 1 ]] ; then
#echo "    location = / {
#        index $USE_STATIC_URL/index.html;
#    }" >> /etc/nginx/conf.d/nginx.conf
#fi

# Finish the Nginx config file
echo "}" >> /etc/nginx/conf.d/nginx.conf

exec "$@"
```

mycustomapp.py

```
from flask import Flask

app = Flask(__name__)

...
```

Just to be clear:
1. When I run the the default image of `tiangolo/uwsgi-nginx-flask:python2.7` everything runs ok without errors. 
2. When I run my custom modified image (with my modified files) my app works fine as expected.
3. The problem is that there is a process of nginx trying to start and is spamming stdout/stderr.
4. At least 3 weeks ago the image ` tiangolo/uwsgi-nginx-flask:python2.7` worked fine for me without any errors.

**Comment by tiangolo** [comment]
Hmm, I think you are using a modified entrypoint based on a previous version of the image. Although I can't quickly spot what are you customizing from the previous original version.

If you need to completely customize/override the Nginx config it's easier now: https://github.com/tiangolo/uwsgi-nginx-flask-docker#overriding-nginx-configuration-completely

The new entrypoint is a bit more error-proof. It doesn't modify the existing nginx.conf, that can lead to problems after restarts, if some of the changes are duplicated, etc: https://github.com/tiangolo/uwsgi-nginx-flask-docker/blob/master/python2.7/entrypoint.sh

**Comment by Aponace** [comment]
I think the change from previous entrypoint to the new one made the error for me and @Askill. Maybe you should consider changing the current image tags to prevent breaking changes in future releases, eg:

`tiangolo/uwsgi-nginx-flask-python-2.7:v1.0.0`

Anyways, I will change my entrypoint. Thanks for the support.

**Comment by tiangolo** [comment]
I'm glad that solved your issue @Aponace.

I announce changes in the releases here: https://github.com/tiangolo/uwsgi-nginx-flask-docker/releases

You can click the "watch" button and select "releases only", and you will receive an email when there's a new release.

There are normally no breaking changes, but also I normally don't expect users to modify the entrypoint, I expect that any additional customization can be done with the configurations, env vars, and prestart script: https://github.com/tiangolo/uwsgi-nginx-flask-docker#custom-appprestartsh

**Comment by dandyweng** [comment]
I had the same issue. Solved by using the latest Dockerfile and entrypoint in the repo. I think that's indeed a breaking change (I didn't modify the entrypoint file).

**Comment by tiangolo** [comment]
Thanks for the report @heiko-braun !

There are tags for each build date now :tada:  you can check more in the note in the main docs. That way you can pin to a very specific image from a very specific date.
