### ISSUE TITLE
Changing `WORKDIR` causes uWSGI to not find app

### ISSUE THREAD

**Issue by DanielGibbsNZ** [tiangolo/uwsgi-nginx-flask-docker#14]
I have a `Dockerfile` with the following contents:

    FROM tiangolo/uwsgi-nginx-flask:python3.6
    COPY app /app
    COPY foo /tmp/foo
    WORKDIR /tmp/foo
    RUN some other commands
    # More RUN commands

When I build this image I get the following errors:

    ModuleNotFoundError: No module named 'main'
    unable to load app 0 (mountpoint='') (callable not found or import error)

Why does the `WORKDIR` in my `Dockerfile` affect the functionality of the base image?

My apologies if this is obvious or expected behaviour; I don't have much Docker experience.

**Comment by tiangolo** [comment]
You are changing the `WORKDIR`, it is used by uWSGI to know where to look for an app.

Change your `Dockerfile` to:

```Dockerfile
FROM tiangolo/uwsgi-nginx-flask:python3.6
COPY app /app
COPY foo /tmp/foo
WORKDIR /tmp/foo
RUN some other commands
# More RUN commands

WORKDIR /app
```

Let me know if that solved your problem.

**Comment by DanielGibbsNZ** [comment]
Yeah that works; I'm still a bit confused as to why I need to do that though. Doesn't the uWSGI config tell it where to find the app?

**Comment by tiangolo** [comment]
Yes, but it tells it where to find the app relative to the current directory. 

Technical details (feel free to skip them): Actually, it doesn't tell uWSGI about a file or directory but a "Python module" to import and use. So, it could be in the same directory or you could have your app "installed", but that would probably be more complicated than just going to that directory.

**Comment by DanielGibbsNZ** [comment]
Ah ok; I think I was missing the fact that the entrypoint was running `supervisord` (and therefore `uwsgi` itself). Thanks for explaining!

**Comment by tiangolo** [comment]
Cool! I'm glad to help. Thanks for replying back and closing the issue. :heavy_check_mark:

**Comment by emesterhazy** [comment]
I'm having an issue similar to above which I can't seem to resolve. I'm adding my application to a custom directory and modifying the Dockerfile as shown below. Unfortunately I'm stuck with this error message:

```
ModuleNotFoundError: No module named 'app'
unable to load app 0 (mountpoint='') (callable not found or import error)
```

Here's the Dockerfile:

```
FROM tiangolo/uwsgi-nginx-flask:python3.6

ENV UWSGI_INI /custom_name/uwsgi.ini

COPY ./custom_name /custom_name

WORKDIR /custom_name

ENV PYTHONPATH=/custom_name

```

Thoughts?
