### ISSUE TITLE
Containerizing a package based app with a name other than `app`

### ISSUE THREAD

**Issue by connerxyz** [tiangolo/uwsgi-nginx-flask-docker#142]
I've got an app I've been developing locally with a package-name specific to the project.  And now am trying to containerize it.

I've updated all the `app` references in the docker files from the package example to `<project-name>`, but when I hit localhost I get 

> "Hello World from Flask in a uWSGI Nginx Docker container with Python 3.7 (default)" 

Going into `docker logs ...` looks like nginx is still serving out of `/app`.

My directory structure looks like this:

```
project-name/
  setup.py
  projectname/
    api/
    static/
    templates/
    __init__.py
    uwsgi.ini
  docker-compose.override.yml
  docker-compose.yml
  Dockerfile
  ...
```

Any advice? Thanks!

**Comment by TorPeeto** [comment]
I'm in the exact same boat at the moment.

**Comment by connerxyz** [comment]
I "solved" it by just adapting my package to what the image expects (i.e. `project/app/app/main.py`).  I don't love it, but it works.  

When I have a bit a spare time I plan on going upstream and working with the image to try and adapt it to my preferences.

**Comment by TorPeeto** [comment]
After I posted here, I got it to work.  

[Here](https://github.com/tiangolo/uwsgi-nginx-docker#custom-app-directory) are the magic steps.

**Comment by tiangolo** [comment]
Yep, what @TorPeeto says, it's there in the docs. :memo: :nerd_face:
