### ISSUE TITLE
Bash no longer working in 'prestart.sh'

### ISSUE THREAD

**Issue by tedivm** [tiangolo/uwsgi-nginx-flask-docker#144]
I had previously written a 'prestart.sh' script using bash that worked great, but now it's giving out errors. A little digging shows that the `#!/usr/bin/env bash` is being ignored and instead sh is being used now.

**Comment by tedivm** [comment]
I'm not even sure what version of SH- statements that work locally are failing in the containers.

**Comment by tiangolo** [comment]
One thing that you could do is pin your Docker image to a specific version, as described in the Note here: https://github.com/tiangolo/uwsgi-nginx-flask-docker#supported-tags-and-respective-dockerfile-links

That way you can be sure that you are always using the exact same base image, and then update it by hand.

If you are still having issues, please create a simple and minimal self-contained example that shows the problem, that way I'll be able to give it a try.
