### ISSUE TITLE
handle large concurrent requests

### ISSUE THREAD

**Issue by guylissak** [tiangolo/uwsgi-nginx-flask-docker#145]
Hi,

first thanks for your great work.
second, hope you can help me with my question :)
I'm building a scalable flask service for my application, and it should handle large amount of concurrent requests, Im using your latest docker image of course...
at first I had issues with the listen queue when i sent more than 1xx requests, i was able to resolve it and enlarged the listen queue, however i see strange behavior.
I have a backend operation on my flask app that takes 3000ms for 1 request, i enable threads as well and use 16 threads in the uwsgi.ini.
the expected behavior was that when i sent 16 concurrent requests i will get a response for all after 3000ms, however only the first few responses are finished within 3000ms and the next ones are increasing in linear way.
for example 10 requests will return after 8,000ms, 5 after 6,000ms and so on...

my uwsgi.ini file is configured this way:
[uwsgi]
module = main
callable = app
listen = 4096
enable-threads = True
threads = 16

p.s
1. i also tried to change the proccesses number to 16 but results did not improve
2. if instead of running backend calculation in the app i switch to delay of 0.2ms for e.g it works as expected and all the 16 responses return in 200ms

appreciate you help,
thanks!

**Comment by tiangolo** [comment]
Hey! I'm glad it's being useful.

The first thing that might be happening is that you are already using all the available CPU. So, even if you add more processes, they still have to wait for the CPU to be available. You could probably check that with `top` or `htop` in your machine.

In that case, you would want to add a background task queue with Celery or similar and do the long processing in a distributed way.

On the other side, you could probably improve performance by switching from Flask to FastAPI.
