### ISSUE TITLE
flask_restful module not found

### ISSUE THREAD

**Issue by 2prashantstha** [tiangolo/uwsgi-nginx-flask-docker#146]
Hello,
I have an issue regarding flask_restful. I have had already installed flask and flask_restful, flask is working but if i work on flask_restful program as importing Resource, Api from flask_restful.
And whenever i try to run this code from terminal . It says No Module found 'flask_restful', even if i installed already.
if i check
 >>>pip freeze

aniso8601==7.0.0
asn1crypto==0.24.0
Click==7.0
cryptography==2.1.4
enum34==1.1.6
Flask==1.1.1
Flask-RESTful==0.3.7
idna==2.6
ipaddress==1.0.17
itsdangerous==1.1.0
Jinja2==2.10.1
keyring==10.6.0
keyrings.alt==3.0
MarkupSafe==1.1.1
pycrypto==2.6.1
pygobject==3.26.1
pytz==2019.1
pyxdg==0.25
SecretStorage==2.3.1
six==1.12.0
Werkzeug==0.15.4

...... i have Flask-RESTful==0.3.7..

Please kindly provide me solution, i am stucked in this

**Comment by 2prashantstha** [comment]
solution found.

**Comment by nsaripalli** [comment]
Hi, @2prashantstha 
I am running into this same issue. By any chance do you remember what your issue was?

**Comment by ranamanas** [comment]
hello @2prashantstha  i am also facing same issue, could you please tell the solution.
