### ISSUE TITLE
Docker bash is not working

### ISSUE THREAD

**Issue by vagarwal77** [tiangolo/uwsgi-nginx-flask-docker#147]
I have created and deployed our application with below DockerFile and every thing works fine but after running the container, we are not able to list any command or CD to any directory within the container... what is missng in my DockerFile? 
##### Docker bash issue
[ec2-user pdx_eos]$ docker exec -t 2077c25fbfc0 bash

root@2077c25fbfc0:/app/pdx_eos# ls
^C
root@2077c25fbfc0:/app/pdx_eos# cd /var/log/cyclops
^C
##### DockerFile
FROM tiangolo/uwsgi-nginx-flask:python3.7
RUN apt-get update -y && ACCEPT_EULA=Y apt-get install -y \
    wget \
    apt-transport-https \
    python3-dev \
    software-properties-common \
    python3-pip
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

RUN mkdir -p /opt/eos/secrets
RUN mkdir -p /var/log/cyclops

// GIT commands which had been removed

WORKDIR pdx_eos

RUN pip3 install pipenv
ENV EOS_HOME `pwd`
RUN pipenv install
ENV PATH $PATH:./scripts
ENV PYTHONPATH `pwd`
ENV DEPLOY_TYPE aws
ENV JERRY_API_HOST 10.255.5.20
RUN make dblisten
RUN echo '### DB watcher waiting for LISTEN/NOTIFY events...'
ENTRYPOINT [ "make", "run-cyclops" ]

**Comment by tiangolo** [comment]
You are overriding the entrypoint with a custom `make` command. That would break the container.

You probably have to put that in a `RUN` directive above.
