### ISSUE TITLE
Use nginx as a separate independent container

### ISSUE THREAD

**Issue by swastikaa-in** [tiangolo/uwsgi-nginx-flask-docker#148]
Hi,

In our environment we already have nginx running as a separate container, so is it possible to exclude nginx and use only the application server component of this image. 

I mean we want to use the nginx for routing outside the image and use uwsgi for serving the flask app.

**Comment by tiangolo** [comment]
It would probably be easier to use a `Dockerfile` based on the standard Python image and installing uWSGI or Gunicorn on top, instead of having Nginx and Supervisor and all the extra stuff that comes with this image.
