### ISSUE TITLE
Question: Where, when and how main.py is executed?

### ISSUE THREAD

**Issue by innjoshka** [tiangolo/uwsgi-nginx-flask-docker#149]
I want to figure out how flask server is executed. I see that supervisor up nginx and uwsgi servers, but nothing about by whom uwsgi.ini is executed and where is command for executing main.py. That's no so easy for people who are a little far from web, so I believe it will help anyone else. 

By the way, I cannot make my relative imports from app workdir. Can you help me with what should I do to do it? 
my folder structure is 
```
.
├── app
│   ├── app
│   │   ├── api
│   │   │   ├── api.py
│   │   │   ├── endpoints
│   │   │   │   ├── __init__.py
│   │   │   │   └── user.py
│   │   │   ├── __init__.py
│   │   │   └── utils.py
│   │   ├── core
│   │   │   ├── app_setup.py
│   │   │   ├── database.py
│   │   │   └── __init__.py
│   │   ├── __init__.py
│   │   ├── main.py
│   │   └── models
│   │       ├── __init__.py
│   │       └── user.py
│   └── uwsgi.ini
└── Dockerfile
```

```
root@fbb14de4a453:/app# ls
app  uwsgi.ini
root@fbb14de4a453:/app# python3 app/main.py
Traceback (most recent call last):
  File "app/main.py", line 5, in <module>
    from .core import app_setup
ModuleNotFoundError: No module named '__main__.core'; '__main__' is not a package
```

Thanks a lot for any help and for the great project and work.

**Comment by tiangolo** [comment]
The uWSGI is set up in the parent image.

Here: https://github.com/tiangolo/uwsgi-nginx-docker/blob/master/python3.7/supervisord.conf#L5

With env vars from here: https://github.com/tiangolo/uwsgi-nginx-docker/blob/master/python3.7/Dockerfile#L120

With this file: https://github.com/tiangolo/uwsgi-nginx-docker/blob/master/python3.7/uwsgi.ini

And this one: https://github.com/tiangolo/uwsgi-nginx-docker/blob/master/python3.7/app/uwsgi.ini

That is then overwritten by this one: https://github.com/tiangolo/uwsgi-nginx-flask-docker/blob/master/python3.7/app/uwsgi.ini

I hope that helps!
