### ISSUE TITLE
Changing block size

### ISSUE THREAD

**Issue by TodimuJ** [tiangolo/uwsgi-nginx-flask-docker#151]
Hey there,

I'm currently facing the same issue of "invalid request block size: 5047 (max 4096) .... skip". I was using the "python3.6-alpine3.7" image in my Dockerfile so switched to just the "python3.6" image and the issue still persists. How would I be able to change the block size and what file?

Cheers!

**Comment by tiangolo** [comment]
Hey @TodimuJ , if you are having issues please provide a simple self-contained example that generates the error, to be able to check it.
