### ISSUE TITLE
How to get the correct external ip in the uwsgi logs

### ISSUE THREAD

**Issue by mbtronics** [tiangolo/uwsgi-nginx-flask-docker#152]
I have a setup with this docker container behind an nginx proxy. In the uwsgi logs, only the docker bridge ip is visible:
[pid: 157|app: 0|req: 1/2] 172.21.0.1 () {44 vars in 521 bytes} [Wed Sep 11 08:08:10 2019] GET /

The following headers are configured in the nginx proxy:
            proxy_set_header        X-Real-IP $remote_addr;
            proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header        X-Scheme $scheme;
            proxy_set_header        Host $http_host;
            proxy_set_header        X-NginX-Proxy true;

Whatever I try, I never get the correct client ip in the uwsgi logs. Is there something I'm doing wrong or is this just impossible?

**Comment by tiangolo** [comment]
You probably need to configure the container Nginx with these directives: http://nginx.org/en/docs/http/ngx_http_realip_module.html#real_ip_recursive

As described in the docs here: https://github.com/tiangolo/uwsgi-nginx-flask-docker#customizing-nginx-additional-configurations
