### ISSUE TITLE
cannot access outside apis

### ISSUE THREAD

**Issue by lsqpku** [tiangolo/uwsgi-nginx-flask-docker#155]
I set up a very simple project based this image and the project just accesses the tensorflow/serving api. It returned below error(If i don't use the docker and just run my python script, it can return successfully, it seems the failure is caused by uwsgi or nginx, btw, how could I view the uwsgi/nginx logs of the container?, thank you in advance.):
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html><head>
<meta http-equiv="Content-Type" CONTENT="text/html; charset=utf-8">
<title>ERROR: The requested URL could not be retrieved</title>
<style type="text/css"><!-- 
....
</head><body id=ERR_CONNECT_FAIL>
<div id="titles">
<h1>ERROR</h1>
<h2>The requested URL could not be retrieved</h2>
</div>
<hr>

<div id="content">
<p>The following error was encountered while trying to retrieve the URL: <a href="http://192.168.13.128:8501/v1/models/bertv2.1:predict">http://192.168.13.128:8501/v1/models/bertv2.1:predict</a></p>

<blockquote id="error">
<p><b>Connection to 192.168.13.128 failed.</b></p>
</blockquote>

<p id="sysmsg">The system returned: <i>(111) Connection refused</i></p>

<p>The remote host or network may be down. Please try the request again.</p>

**Comment by lsqpku** [comment]
Sorry. This issue is due to proxy setting in docker file. After comment proxy setting, the issue is solved, so I close this issue.

**Comment by tiangolo** [comment]
Thanks for reporting back and closing the issue :+1:
