### ISSUE TITLE
Question: How do I route NGINX and uWSGI logs to files instead of stdout

### ISSUE THREAD

**Issue by simon-k** [tiangolo/uwsgi-nginx-flask-docker#157]
Hi
I would like to put the NGINX and uWSGI logs in log files instead of writing them to stdout because they are polluting my log.

Is there a way to do this? I tried to modify uwsgi.ini but that didn't work. 

Alternatively is there a way to change the log format? I managed to change the uWSGI log format in uwsgi.ini but how do I change the NGINX log format?

**Comment by NejcZupec** [comment]
@simon-k If you wanna change the NGINX log format, you will have to override the NGINX config. More info: https://github.com/tiangolo/uwsgi-nginx-flask-docker#overriding-nginx-configuration-completely

Here is an example of `app/nginx.conf` file that outputs logs as JSON:
```
user nginx;
worker_processes 1;
error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;

    log_format main escape=json
      '{'
        '"time":"$time_iso8601",'
        '"remote_addr":"$remote_addr",'
        '"request":"$request",'
        '"status": $status,'
        '"body_bytes_sent":$body_bytes_sent,'
        '"request_time":$request_time,'
        '"upstream_response_time": "$upstream_response_time",'
        '"http_referrer":"$http_referer",'
        '"http_user_agent":"$http_user_agent",'
        '"http_ssl_proto":"$http_x_ssl_protocol",'
        '"http_ssl_cipher":"$http_x_ssl_cipher"'
      '}';

    access_log /var/log/nginx/access.log main;

    server {
        listen 80;
        location / {
            try_files $uri @app;
        }
        location @app {
            include uwsgi_params;
            uwsgi_pass unix:///tmp/uwsgi.sock;
        }
        location /static {
            alias /app/static;
        }
    }

    client_max_body_size 0;
}
daemon off;

```

**Comment by szepnapot** [comment]
Well, even after overriding the `nginx.conf` and adding the line:
`access_log /var/log/nginx/access.log main;` it still logs to STDOUT. I want nginx to log to file, so I can add a fail2ban container to my setup. How can I do this?

**Comment by tiangolo** [comment]
Thanks for the help here everyone! :cake: 

The log files are configured in the parent image, in Supervisord, here: https://github.com/tiangolo/uwsgi-nginx-docker/blob/master/python3.7/supervisord.conf

So you could probably override it there.

**Comment by vlasvlasvlas** [comment]
Hi, i was wondering how i can leave the nginx and uwsi log files not only in files instead of stdout, but also, that these files are kept on my server instead of flushed after a docker restart / delete reconstruct, thanks :)
