### ISSUE TITLE
No support for HTTPs

### ISSUE THREAD

**Issue by benbarbour** [tiangolo/uwsgi-nginx-flask-docker#16]
I'm trying to figure this out now. I would prefer not to check the keys into my repo or bake them into the image.

As it stands, it looks like I'll have to overwrite entrypoint.sh so that it writes a different nginx.conf that points to a cert and a key in a volume that runner of the container can create. I'm pretty new to docker though... any recommendations?

**Comment by tiangolo** [comment]
Yes, leave the problem to a different component / service (Docker container) in your system. 

TLS certificate handling is a complex thing per se.

If you have more than one thing on your server you won't want this image to handle HTTPS directly, as it will force you to have only this image listening on the HTTPS port (443).

The best and simplest way to deal with HTTPS for me has been setting up a TLS / SSL termination proxy. You set up a Nginx / Haproxy / Traefik proxy that has all the certificates and redirects for each service that should handle it.

And then you configure it to use Let's encrypt and renew the certificates automatically every some months (3 I think).

You could try with [Rancher](http://rancher.com/), it has a "stack" in the "catalog" that can handle all the Let's encrypt certificate generation and renovation for you. And it has some integrated "load balancers", they are just a Haproxy with a web UI they provide. From there, you can set up all the HTTPS handling, even for different domains, etc. And pass the control to the appropriate service.

If not with Rancher, I would try [Traefik](https://github.com/containous/traefik). They are kind of "made for Docker". With automatic Let's encrypt, etc.

But, the same as I would put the database in a different service / container, I would treat HTTPS with certificate renewal as a problem big enough as to have its own service / container.

**Comment by benbarbour** [comment]
Thanks for the advice! The app is just for internal use so I didn't go all the way with Rancher or Traefik. Instead I just set up nginx on the host to proxy https requests to the container. It was very simple to set up.

**Comment by tiangolo** [comment]
Ok, cool. Were you able to solve your problem?

**Comment by benbarbour** [comment]
Yes, thanks

**Comment by tiangolo** [comment]
Great. I will close this issue now.
