### ISSUE TITLE
pip install --upgrade pip error

### ISSUE THREAD

**Issue by mxyue** [tiangolo/uwsgi-nginx-flask-docker#161]
tiangolo/uwsgi-nginx-flask   python3.7 
IMAGE ID: fb645b1beeca

RUN  pip install --upgrade pip

ERROR: Could not install packages due to an EnvironmentError: [Errno 22] Invalid argument: '/usr/local/lib/python3.7/site-packages/pip-19.2.3.dist-info/'

----

IMAGE ID: e4062d338604 can install success

**Comment by tiangolo** [comment]
Hmm, I just tried with:

```Dockerfile
FROM tiangolo/uwsgi-nginx-flask:python3.7

RUN pip install --upgrade pip
```

And it seems to be working correctly. Maybe it could be an issue with your network or firewall?
