### ISSUE TITLE
Python 3.8

### ISSUE THREAD

**Issue by Sohalt** [tiangolo/uwsgi-nginx-flask-docker#162]
Is there an ETA for a version supporting python 3.8?

**Comment by GrahamCampbell** [comment]
Ping. :)

**Comment by KingDarBoja** [comment]
Not until `tiangolo/uwsgi-nginx-docker` docker support it. There is a open issue [about it](https://github.com/tiangolo/uwsgi-nginx-docker/issues/73) on that repo.

**Comment by tiangolo** [comment]
There's a new Python 3.8 version now :rocket: :tada:
