### ISSUE TITLE
start.sh location? 

### ISSUE THREAD

**Issue by shubhamkalra27** [tiangolo/uwsgi-nginx-flask-docker#163]
the dockerfile here ends with CMD ["/start.sh"]

https://github.com/tiangolo/uwsgi-nginx-flask-docker/blob/master/python3.6-alpine3.7/Dockerfile 

where is this file? i see prestart but not start.sh?

**Comment by KingDarBoja** [comment]
The docker file already states the location:

> _Run the start script provided by the parent image tiangolo/uwsgi-nginx._ 

[start.sh source file](https://github.com/tiangolo/uwsgi-nginx-docker/blob/master/python3.6-alpine3.7/start.sh)

**Comment by tiangolo** [comment]
Yep, just what @KingDarBoja said. :point_up:
