### ISSUE TITLE
how to install java inside this container

### ISSUE THREAD

**Issue by lcwj3** [tiangolo/uwsgi-nginx-flask-docker#164]
Hi, there, very nice work, it saved me a lot!
Here is my problem:
I am trying to use your image as a base, but I need java in my code, I have tried apt-get but it says apt not found. So how can I install java based on your image? or say how can I use apt install in this container? 

Thanks for your attention and looking forward to your kind reply.

**Comment by lcwj3** [comment]
Sorry to interrupt, just found this is an alpine linux, I can simply do this by adding `RUN apk --update add openjdk8-jre`.
 Close this now, thanks.

**Comment by tiangolo** [comment]
Thanks for reporting back and closing the issue :+1:
