### ISSUE TITLE
docker-slim bind() error with uwsgi-nginx:python3.6

### ISSUE THREAD

**Issue by labi112** [tiangolo/uwsgi-nginx-flask-docker#165]
Hi Tiangolo,

I am using the uwsgi-nginx:python3.6 image to build a microservice. The size of 1.23 GB is quite large so, I tried to slim it with docker-slim.
Unfortunate docker-slim deletes necessary folders even with http-probes provided.

> bind(): No such file or directory [core/socket.c line 230]

Do you have any experience regarding docker-slim?

Thank you for your support.

**Comment by tiangolo** [comment]
Well, yeah, you found the problem... The slim versions don't have many dependencies required for some Python packages, etc.

But also, have in mind that most of the layers are shared by other containers. So, if you have a Postgres, or a Redis, or almost anything else, they all share most of the layers, as they are all based on the same Debian.
