### ISSUE TITLE
Set configuration by location 

### ISSUE THREAD

**Issue by eamanu** [tiangolo/uwsgi-nginx-flask-docker#166]
Hi,

I am trying to poweroff the access_log for a location, but I can not override that.

I create a nginx-custom.conf with:
```
location /my/path/{
    access_log off
}
```
Also adding `http{}` and `server{}` key but it's not woking

How could I do?

**Comment by tiangolo** [comment]
The access log is probably generated by your Flask app, so it would be in your Python code.

**Comment by eamanu** [comment]
Hi @tiangolo  I will close the issue because seems to be a not bug.
