### ISSUE TITLE
Not able to run Flask+NGINX container in openshift due to supervisord permissions

### ISSUE THREAD

**Issue by vikaskhengare** [tiangolo/uwsgi-nginx-flask-docker#167]
Hi Team,

I am able to build and run the docker container on my local machine but when I deploy same image on openshift then pod creation fails due to following error,

> 

Traceback (most recent call last):
--
  | File "/usr/bin/supervisord", line 11, in <module>
  | load_entry_point('supervisor==3.3.1', 'console_scripts', 'supervisord')()
  | File "/usr/lib/python2.7/dist-packages/supervisor/supervisord.py", line 365, in main
  | go(options)
  | File "/usr/lib/python2.7/dist-packages/supervisor/supervisord.py", line 375, in go
  | d.main()
  | File "/usr/lib/python2.7/dist-packages/supervisor/supervisord.py", line 78, in main
  | info_messages)
  | File "/usr/lib/python2.7/dist-packages/supervisor/options.py", line 1398, in make_logger
  | stdout = self.nodaemon,
  | File "/usr/lib/python2.7/dist-packages/supervisor/loggers.py", line 346, in getLogger
  | handlers.append(RotatingFileHandler(filename,'a',maxbytes,backups))
  | File "/usr/lib/python2.7/dist-packages/supervisor/loggers.py", line 172, in __init__
  | FileHandler.__init__(self, filename, mode)
  | File "/usr/lib/python2.7/dist-packages/supervisor/loggers.py", line 98, in __init__
  | self.stream = open(filename, mode)
  | IOError: [Errno 13] Permission denied: '/var/log/supervisor/supervisord.log'

**I have docker file as below,**

`FROM tiangolo/uwsgi-nginx-flask:python3.7

COPY requirements.txt /tmp/
RUN pip install -r /tmp/requirements.txt

COPY ./prestart.sh /app/
COPY ./nginx.conf /etc/nginx/
COPY ./listener-nginx.conf /etc/nginx/conf.d/nginx.conf
COPY ./upload.conf /etc/nginx/conf.d/
COPY ./entrypoint.sh /

RUN chmod 777 /etc/nginx/nginx.conf
RUN chmod 777 /etc/nginx/conf.d/nginx.conf
RUN chmod 777 /etc/nginx/conf.d/upload.conf
RUN chmod 777 /entrypoint.sh
RUN chmod 777 /app/prestart.sh

COPY ./uwsgi.ini /app/

COPY ./app /app/app`

In prestart, entrypoint sh, I don't have mentioned about "supervisord" at all but still it's starting somehow and throwing excetion.

**However on my local, container starts with warning,**

`/usr/lib/python2.7/dist-packages/supervisor/options.py:298: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  'Supervisord is running as root and it is searching '
2020-02-21 19:00:00,365 CRIT Supervisor running as root (no user in config file)
2020-02-21 19:00:00,366 INFO Included extra file "/etc/supervisor/conf.d/supervisord.conf" during parsing
2020-02-21 19:00:00,377 INFO RPC interface 'supervisor' initialized`

How can we overcome/skip the supervisord ?

Thanks in advance!

-Vikas

**Comment by vikaskhengare** [comment]
Hi,

After giving permission to '/var/log/supervisor/' directory this error went away.

Now usgi throwing error while starting,

> 

--
  | lock engine: pthread robust mutexes
  | thunder lock: disabled (you can enable it with --thunder-lock)
  | chown(): Operation not permitted [core/utils.c line 2649]
  | 2020-02-24 18:01:58,892 INFO exited: uwsgi (exit status 1; not expected)

UWSGI configuration printed as follows,

`



[uwsgi]
  | cheaper = 2
  | processes = 16
  | ini = /app/uwsgi.ini
  | module = app.main
  | callable = deployment_audit_app
  | uid = root
  | ini = /etc/uwsgi/uwsgi.ini
  | socket = /tmp/uwsgi.sock
  | chown-socket = root:root
  | chmod-socket = 666
  | hook-master-start = unix_signal:15 gracefully_kill_them_all
  | need-app = true
  | die-on-term = true
  | show-config = true
  | ;end of configuration
 

`

**Comment by vikaskhengare** [comment]
Hi All,

I remove following line and it started working,

  | chown-socket = root:root
  | chmod-socket = 666

My final uwsgi.ini,

> [uwsgi]
> module = app.main
> callable = deployment_audit_app
> uid = nginx
> socket = /app/uwsgi.sock
> hook-master-start = unix_signal:15 gracefully_kill_them_all
> need-app = true
> die-on-term = true
> show-config = true

nginx.conf file as below,

> user  nginx;
> worker_processes  1;
> 
> error_log  /var/log/nginx/error.log warn;
> pid        /var/run/nginx.pid;
> 
> events {
>   worker_connections  1024;
> }
> 
> http {
>   include       /etc/nginx/mime.types;
>   default_type  application/octet-stream;
> 
>   log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
>   '$status $body_bytes_sent "$http_referer" '
>   '"$http_user_agent" "$http_x_forwarded_for"';
> 
>   access_log  /var/log/nginx/access.log  main;
> 
>   sendfile        on;
>   #tcp_nopush     on;
> 
>   keepalive_timeout           300s;
>   proxy_read_timeout          300s;
>   proxy_connect_timeout       300s;
>   proxy_send_timeout          300s;
>   send_timeout                300s;
>   uwsgi_read_timeout          300s;
> 
>   #gzip  on;
> 
>   server {
>     listen 8080;
>     location / {
>         include uwsgi_params;
>         uwsgi_pass unix:///app/uwsgi.sock;
>     }
>   }
> }
> daemon off;

And supervisor conf file as below,

> [supervisord]
> nodaemon=true
> 
> [program:uwsgi]
> **command=/usr/local/bin/uwsgi --ini /app/uwsgi.ini --uid nginx**
> stdout_logfile=/dev/stdout
> stdout_logfile_maxbytes=0
> stderr_logfile=/dev/stderr
> stderr_logfile_maxbytes=0
> 
> [program:nginx]
> command=/usr/sbin/nginx
> stdout_logfile=/dev/stdout
> stdout_logfile_maxbytes=0
> stderr_logfile=/dev/stderr
> stderr_logfile_maxbytes=0
> stopsignal=QUIT

**Comment by tiangolo** [comment]
It's strange, you shouldn't need to change permissions in the container, but maybe if you have other permissions set, custom volumes, or specific policies then you might need to do that.

Anyway, thanks for reporting back with your solution!

If your problem is solved, may we close this issue now?
