### ISSUE TITLE
Enabling http/2?

### ISSUE THREAD

**Issue by peterk** [tiangolo/uwsgi-nginx-flask-docker#170]
Is there a config setting to enable http2 in Nginx in the docker config somewhere?

**Comment by tiangolo** [comment]
You can probably check the Nginx docs, e.g. https://www.nginx.com/blog/http2-module-nginx/ and the docs in this image about updating Nginx configs.

Nevertheless, I would suggest adding a Traefik proxy/load balancer on top. It could also handle automatic HTTPS certificates.

**Comment by peterk** [comment]
Some further research indicates that uwsgi also seems to have to be configured for http2 for it to work. It would be great if this image included configs for http2 as an option.
