### ISSUE TITLE
wrong JWT errors returned

### ISSUE THREAD

**Issue by meanite** [tiangolo/uwsgi-nginx-flask-docker#171]
Hi,

I am new with uwsgi-nginx-flask and i managed to integrate my application relatively easily.
However, i have an error with "errors" returned by the flask_jwt extension that i use to manage authentication. Endpoints are protected with jwt_required() method.

When i run my app, in dev without the docker image, it works, and HTTP 401 errors was returned when users are not authenticated.

But when i run it inside docker image, an HTTP 500 error is returned. In logs, i see that the correct "error" is correctly detected :

` File "/usr/local/lib/python3.7/site-packages/flask_jwt/__init__.py", line 155, in _jwt_required
    headers={'WWW-Authenticate': 'JWT realm="%s"' % realm})
flask_jwt.JWTError: Authorization Required. Request does not contain an access token`

So i expected a 401 is returned, but nginx return a 500.

I am thinking that i missing something with error handler, and its probably obvious, but i can't find something to fix it.

For information, i use flask-restx extension in my app.

Can someone help me ?

Thanks

**Comment by meanite** [comment]
Okay, i need to add this config parameter :

`app.config['PROPAGATE_EXCEPTIONS'] = True`

I close this issue.

**Comment by tiangolo** [comment]
Thanks for reporting back and closing the issue :+1:
