### ISSUE TITLE
python3.7-alpine3.8 still uses python3.6 at runtime

### ISSUE THREAD

**Issue by JuergenGutsch** [tiangolo/uwsgi-nginx-flask-docker#172]
Hi,
First of all, you do a great work with that images and they save me a lot of time :-) 

Because I use the new asyncio API of Python 3.7 I recently needed to update to the python3.7-alpine3.8 image. And it seems the image still uses python3.6.9 at runtime.

At build time the Python path is configured to use Python 3.7.3, which is absolutely fine.
But it seems uWSGI is still kind of linked to Python 3.6.9:
```
*** Starting uWSGI 2.0.17 (64bit) on [Thu Apr 30 14:29:09 2020] ***
compiled with version: 6.4.0 on 01 May 2018 17:28:25
os: Linux-4.19.76-linuxkit #1 SMP Thu Oct 17 19:31:58 UTC 2019
nodename: fad1b842c0c3
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /app
detected binary path: /usr/sbin/uwsgi
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /tmp/uwsgi.sock fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
Python version: 3.6.9 (default, Oct 17 2019, 11:17:29)  [GCC 6.4.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x5649671cffa0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
```

When I write out the Pathon version during build time I get the following:
```
Step 9/11 : RUN python3 --version
 ---> Running in d2fa49f1f0d3
Python 3.7.3
```

I think this is just a configuration thing somewhere in uWSGI

**Comment by madmaze** [comment]
I think that is related to this: https://github.com/tiangolo/uwsgi-nginx-docker#python-37-not-supported-in-in-alpine

**Comment by JuergenGutsch** [comment]
Absolutely! Thanks @madmaze

**Comment by madmaze** [comment]
@tiangolo are you aware of any issue/ticket tracking uwsgi python-3.7 support in alpine?

**Comment by tiangolo** [comment]
Thanks for the discussion here everyone! :coffee:  

There's now an Alpine version with Python 3.8 :rocket: :tada:

**Comment by madmaze** [comment]
:tada: thanks @tiangolo

**Comment by JuergenGutsch** [comment]
Awesome @tiangolo

**Comment by tiangolo** [comment]
Great! :tada: :rocket: 

If the original problem is solved, then you can close this issue :heavy_check_mark:
