### ISSUE TITLE
Enabling DataDog ddtrace

### ISSUE THREAD

**Issue by jwodushek** [tiangolo/uwsgi-nginx-flask-docker#174]
We have a number of flask API's running as docker containers and using this as a base.  We are in the process of implementing DataDog's ddtrace and need to call python as "ddtrace python3".  Is there a way to hijack the entrypoint to do this?

**Comment by tiangolo** [comment]
I'll copy my answer from the duplicate here https://github.com/tiangolo/uwsgi-nginx-docker/issues/79

I don't think there is a way to do that, as uWSGI is the one that calls Python, and it comes with its own built-in Python version.

I think that could be easier to do with https://github.com/tiangolo/meinheld-gunicorn-docker or the corresponding version for Flask https://github.com/tiangolo/meinheld-gunicorn-flask-docker

Then you would override the default call to `gunicorn`: https://github.com/tiangolo/meinheld-gunicorn-docker/blob/master/docker-images/start.sh#L15

With a call to something like `python -m gunicorn`. Then I guess in your case it would be something like `ddtrace python3 -m gunicorn ...`.
