### ISSUE TITLE
Map host folder to docker container folder failed.

### ISSUE THREAD

**Issue by liuxiaojun03** [tiangolo/uwsgi-nginx-flask-docker#179]
I faced on issue that run the docker with -v parameter to map the host folder to container folder failed.the following is my steps.
1. use the docker pull tiangolo/uwsgi-nginx-flask-docker
2. try to run up the container with command,the /webapp already existing in the host machine.
[root@localhost web_service_docker]# docker run -d  -p 80:80 --name web_service tiangolo/uwsgi-nginx-flask:latest -v /webapp:/app
32a7f7190c827794e8dad30ca26c67072dac7d269f880e5a3e3f91d3dcc5a5
3. the 2# no issue report after I run it.but actually the container does not startup with docker ps command.
[root@localhost web_service_docker]# docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
4. If I do not append -v parameter,it can run successfully and also it tested sucessfully.

**Comment by tiangolo** [comment]
Please follow the instructions here: https://github.com/tiangolo/uwsgi-nginx-flask-docker#advanced-development-instructions

Follow them exactly, step by step. And make sure everything is working as described.

Then you can compare what is different in the example from the docs and your own app.
