### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by mlabarre** [tiangolo/uwsgi-nginx-flask-docker#180]
Hello
I tried to build a docker image from uwsgi-nginx-flask-docker but I have an error (of beginner ?):
My application tree is:
```
app/
    app/
        __init__.py
        main.py
    uwsgi.ini
Dockerfile
```
My Dockerfile is:

```
FROM tiangolo/uwsgi-nginx:python3.8-alpine
COPY ./app /app
WORKDIR /app

```
 
When I run the build I've the following error:
$ docker image build - < Dockerfile
```
Sending build context to Docker daemon  3.072kB
Step 1/3 : FROM tiangolo/uwsgi-nginx:python3.8-alpine
---> e92f09433957
Step 2/3 : COPY ./app /app
COPY failed: stat /app/list/data/docker/tmp/docker-builder266521360/app: no such file or directory
```
What is wrong ?
Many thanks

**Comment by mlabarre** [comment]
Image error

**Comment by tiangolo** [comment]
Thanks for reporting back and closing the issue. :+1:
