### ISSUE TITLE
Cannot make CORS works

### ISSUE THREAD

**Issue by jeromepin** [tiangolo/uwsgi-nginx-flask-docker#183]
So I'm building an app using you image `tiangolo/uwsgi-nginx-flask:python3.8` which looks like this (I know the `if` is useless here, I removed all the irrelevant code for simplicity sake) :

```python
  app = Flask(__name__)
  CORS(app)

  @app.route('/', methods=['POST', 'GET', 'OPTIONS'])
  def index():
      if request.method == 'POST':
          return render_template('index.html')
      else:
          return render_template('index.html')
```

And the terminal output is :

```
172.17.0.1 - - [23/May/2020:13:04:43 +0000] "GET / HTTP/1.1" 200 505 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36" "-"
[pid: 15|app: 0|req: 1/1] 172.17.0.1 () {54 vars in 900 bytes} [Sat May 23 13:04:43 2020] GET / => generated 505 bytes in 20 msecs (HTTP/1.1 200) 3 headers in 112 bytes (2 switches on core 0)
172.17.0.1 - - [23/May/2020:13:04:45 +0000] "OPTIONS / HTTP/1.1" 400 658 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36" "-"
```

What seems weird to me is the preflight request never goes to uwsgi (like the `GET /` did).

I tried :
* with and without listing `OPTIONS` in `methods=[]`
* with and without handling the `OPTIONS` in a conditional block (`elif request.method == 'OPTIONS'`) with appropriate response headers
* responding to the preflight request directly in nginx (without forwarding it to uwsgi)

Nothing worked 😞 

I usually don't have issues with CORS because flask_cors does all the magic, but this time, I can't figure out what I'm missing.

**Comment by JohnStratoudakis** [comment]
I am having this problem as well - but from what I see online, don't we have to modify the nginx.conf that is part of the docker image?

**Comment by jeromepin** [comment]
> I am having this problem as well - but from what I see online, don't we have to modify the nginx.conf that is part of the docker image?

Yeah, it's usually the application which handle CORS but hey, I was trying anything that came to my mind 🤷‍♂️

**Comment by tiangolo** [comment]
Are you calling your API from JS? Because if it is loading a URL with rendered HTML, your browser will just call directly.

Otherwise, if you are sending credentials, you will have to set some origins (`*` won't work with credentials), I guess you can check here: https://flask-cors.readthedocs.io/en/latest/#resource-specific-cors

**Comment by jeromepin** [comment]
@tiangolo My bad, maybe I provided a minimal working example stripped to much ! It returns HTML only on GET. For POST requests, it returns JSON (with appropriate content-type). And I don't send credentials. Do you have any idea what the catch is ?

**Comment by tiangolo** [comment]
I would guess you are sending what CORS refers to "simple requests": https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Simple_requests

Check all that page, it will probably help to understand what could be happening, what should be happening, etc.
