### ISSUE TITLE
Is there way to install and configure uwsgi/nginx/flask in the docker when needing to use the different docker image?

### ISSUE THREAD

**Issue by gojoin** [tiangolo/uwsgi-nginx-flask-docker#185]
Hi sir, 

As we need to use nvidia-docker images for running program with GPU, so we can not use this great image directly.
To achive the same result of uwsgi-nginx-flask-docker, is there way to install and configure uwsgi/nginx/flask in the docker from scratch? 
Providing the detail steps would be much appreciated! Thanks!

**Comment by gojoin** [comment]
The nvidia-docker image we used is based on ubuntu.

**Comment by tiangolo** [comment]
You would have to install everything directly, but in that case, it might be simpler to use Meinheld instead of uWSGI, you can probably copy the ideas from this one: https://github.com/tiangolo/meinheld-gunicorn-docker
