### ISSUE TITLE
How can i use this container with the environment variables of Heroku like $PORT ...

### ISSUE THREAD

**Issue by hackatechs** [tiangolo/uwsgi-nginx-flask-docker#188]
Thanks for this project :) , i am new in docker. How can i use my container with the environment variables defined in Heroku ? :(  And i get 502 bad gateway in development environment (localhost), how i can solve this error ?

**Comment by tiangolo** [comment]
You can probably check the Docker tutorials: https://docs.docker.com/get-started/

VS Code also has good tutorials.
