### ISSUE TITLE
Connection aborted when accessing a HTTPS source

### ISSUE THREAD

**Issue by tzizel** [tiangolo/uwsgi-nginx-flask-docker#19]
Hi,

using this image allowed me to properly start my app. However it kept failing at a certain point. I figured out that there is a problem at accessing an HTTPS source.

I isolated the respective part of my app and started it in a container. I basically just downloads a file from an S3 resource when I get the following error:

`botocore.vendored.requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))`

However starting the flask app locally with cmd on my Windows it works perfectly fine. I also tried it on a regular Apache2 server and got the same issue so I think it has to do something with uwsgi or the reverse proxy. In the flask code below you can see that I use a custom endpoint for S3 and not the service on AWS and this server is served with SSL. Could that be an issue? Can I solve this problem by changing the configuration on this image? Thank you very much.

```
app = Flask(__name__)

@app.route('/', methods=['GET', 'POST'])
def index():
    conn = boto3.client('s3', region_name="eu-west-1", endpoint_url="https://endpoint", aws_access_key_id=accesskey, aws_secret_access_key=secretkey)
    conn.download_file('mytestbucket22', 'aggregated.csv', 'aggregated.csv')
    return 'ok'

if __name__ == '__main__':
	app.run(host='0.0.0.0', debug=True)
```

**Comment by tiangolo** [comment]
Try to run it on Windows not in a development environment. I mean, don't do any `python main.py` or `flask run ...`.

Just let the image do its thing. That way, we'll be able to know if it is something related to uWSGI or not.

But it seems a lot to me like a problem outside the image, in some proxy or firewall between your image and your S3 bucket.

**Comment by tzizel** [comment]
Thank you. It was actually a problem with the signature of the Amazon API. Sorry for bothering you and thanks for your help.

**Comment by tiangolo** [comment]
Thanks for replying back and closing the issue.
