### ISSUE TITLE
Broken pipe in uwsgi

### ISSUE THREAD

**Issue by mlabarre** [tiangolo/uwsgi-nginx-flask-docker#190]
Hello
I've built a little automation application which uses Selenium to dialog with web site. Request can require some calls to different endpoints. When elapsed exceeds 30s, original request stops with a HTPP status 499, so wsgi failed with a broken pipe when it try to send the response.
I've used all well known parameters of nginx/uwsi to grow response timeout but no success.
nginx parms:
```
            uwsgi_read_timeout 300s;
            uwsgi_request_buffering on;
            proxy_connect_timeout 300s;
            proxy_send_timeout 300s;
            proxy_read_timeout 300s;
            send_timeout 300s;
            fastcgi_read_timeout 300s;
```
uwsgi.ini parms :
```
module = app.main
callable = app
enable-threads = true
harakiri = 120
http-timeout = 120
```

Have you an idea ?
Many thanks

**Comment by tiangolo** [comment]
And if you check the logs, what is returning the 499 error? Nginx or uWSGI?

Something else you can try is the alternative image: https://github.com/tiangolo/meinheld-gunicorn-flask-docker
