### ISSUE TITLE
Duplicate PYTHONPATH

### ISSUE THREAD

**Issue by puggan** [tiangolo/uwsgi-nginx-flask-docker#191]
This section
https://github.com/tiangolo/uwsgi-nginx-flask-docker/blob/3ab2429620bd502c40fdf5c6d61527daa294a855/docker-images/entrypoint.sh#L39-L44

is a duplicate of 
https://github.com/tiangolo/uwsgi-nginx-docker/blob/4d966c0dc4d1fd29298acd01303c9225f1c11341/docker-images/entrypoint.sh#L64-L69
![Screenshot from 2020-06-19 15-23-49](https://user-images.githubusercontent.com/866668/85137088-ed78f600-b240-11ea-8b96-40b73bfa900d.png)

that's already executed due to this line:
https://github.com/tiangolo/uwsgi-nginx-flask-docker/blob/3ab2429620bd502c40fdf5c6d61527daa294a855/docker-images/entrypoint.sh#L4

So line 39-44 should be safe to remove?

**Comment by tiangolo** [comment]
Not really because that line creates a variable for that internal process, and we need the variable to be set before the `exec "$@"` so we need the duplication there :pensive:

**Comment by puggan** [comment]
ah, my bad, 
with `. /uwsgi-nginx-entrypoint.sh` the exports leaks out,
with just `/uwsgi-nginx-entrypoint.sh` the exports is contained in that script.
