### ISSUE TITLE
SSL gives 502.

### ISSUE THREAD

**Issue by mohovkm** [tiangolo/uwsgi-nginx-flask-docker#193]
HI!
I use this template to run the container with a secure SSL connection. - Just a simple app "`return 'hello, vasya' `"
All fine, when I run it on localhost, or on a server when I open it via IP, but when I try to open site via domain name over https, I get an error:
**502 Bad Gateway.**

And in Nginx logs, I see  **_no live upstreams while connecting to upstream_**

It's interesting because I have 10 containers with FastAPI on the same server all with HTTPS and all works fine.

For SSL proxy I use this solution: 
https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion

What do you think about it? Is it seems, like a bug?

---UPD---
I checked it with my own Dockerfile and SSL works fine

**_Dockerfile:_**
```
FROM python:3.7.2-slim

COPY ./app /app
WORKDIR "/app"

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

ENTRYPOINT ["python"]
CMD ["main.py"]
```

**Comment by tiangolo** [comment]
If I understand correctly, you are adding SSL to Nginx-proxy, right?

Then the problem would be there and not in this container. Either way, I would suggest you add TLS termination in the external proxy/load balancer (in this case, Nginx-proxy), not to the container directly. As it needs exclusive control of the IP.

I would also recommend [Traefik](https://doc.traefik.io/traefik/) for TLS termination with automatic HTTPS certificates from Let's Encrypt.
