### ISSUE TITLE
What's the adcantage of this repo over meinheld-gunicorn-flask?

### ISSUE THREAD

**Issue by nalzok** [tiangolo/uwsgi-nginx-flask-docker#194]
It is indicated in the README.md that

> #### If you need Flask
> 
>If you need to use Flask (instead of something based on ASGI) and you need to have the best performance possible, you can use the alternative image: [**tiangolo/meinheld-gunicorn-flask**](https://github.com/tiangolo/meinheld-gunicorn-flask-docker).
>
> **tiangolo/meinheld-gunicorn-flask** will give you about 400% (4x) the performance of this image (**tiangolo/uwsgi-nginx-flask**).
>
> It is very similar to **tiangolo/uwsgi-nginx-flask**, so you can still use many of the ideas described here.

If meinheld-gunicorn-flask is significantly faster, which features are keeping us here?

**Comment by tiangolo** [comment]
No idea. :shrug: I wonder that myself.

Probably just that you might already have this deployed somewhere, or that you need uWSGI because it's a lot older and you don't want to change to something you haven't tried yet.
