### ISSUE TITLE
The app is being run twice, due to which models, seeders and everything else is running twice

### ISSUE THREAD

**Issue by vivekkaushal99** [tiangolo/uwsgi-nginx-flask-docker#195]
I am using version 3.6 of the current image.

The app is running twice in production mode. I have set DEBUG = False and ENV = 'production' in config.py as well as I've set FLASK_DEBUG = 0 in docker environment. I am running in production and not using app.run method. My main.py is something like this:

`from flask import Flask`
`app = Flask(__name__)`
`print('*** HELLO WORLD ***')`

The print statement is printing twice. I understand the reloader is used in Debug mode in Flask, but I've tried to disable Debug mode in every way. Is this something related to the current image I am using?

**Comment by tiangolo** [comment]
That's because by default it starts 2 uWSGI worker processes. https://github.com/tiangolo/uwsgi-nginx-flask-docker#custom-uwsgi-process-number
