### ISSUE TITLE
UWSGI with Python 3.7 in Dockerfile

### ISSUE THREAD

**Issue by abobakrahmed** [tiangolo/uwsgi-nginx-flask-docker#196]
Hi, Tiangolo
          Great work brother , hope you're the best , i have isse when run Docker file contain "Python 3.7 , Uwsgi , Postgres, Nginx "

Build command by jenkins , everything running but when docker logs -f app showing this 

**"2020-07-16 00:34:26,763 INFO spawned: 'uwsgi' with pid 480
[uWSGI] getting INI configuration from /home/app/payouts_portal/uwsgi.ini
2020-07-16 00:34:27,774 INFO success: uwsgi entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)"**

**Comment by tiangolo** [comment]
I'm sorry, I'm not sure I understand what's the problem. Maybe you could write a simple minimal way to reproduce the issue?
