### ISSUE TITLE
Image python3.7-alpine3.8 is using python3.6

### ISSUE THREAD

**Issue by alsoba13** [tiangolo/uwsgi-nginx-flask-docker#198]
Hey there,
I just wanted to notice that uwsgi in image `python3.7-alpine3.8` is using python3.6.

You may check it easily by running:
`$ docker run --rm tiangolo/uwsgi-nginx-flask:python3.7-alpine3.8`

At some point you'll see this line: 
`Python version: 3.6.9 (default, Oct 17 2019, 11:17:29)  [GCC 6.4.0]`

I guess that it has something to do with [this PR](https://github.com/tiangolo/uwsgi-nginx-flask-docker/pull/82/files#diff-4801f0d5327623a6d634956b932f116cR33).

I'm not sure if you want to rebuild it or you will leave as is.

For anyone facing problems with it, both using `python3.8-alpine` and migrating it to `python3.7` worked for me.

**Comment by alsoba13** [comment]
Nevermind, I just read this https://github.com/tiangolo/uwsgi-nginx-flask-docker/issues/172

**Comment by tiangolo** [comment]
Thanks for reporting back and closing the issue :+1:
