### ISSUE TITLE
Can't get async multiprocessing working

### ISSUE THREAD

**Issue by anurbol** [tiangolo/uwsgi-nginx-flask-docker#199]
I have this route

```
from multiprocessing import Process

# -- snip --

@app.route('...')
def start():
    process = Process(target=long_operation, daemon=False)
    process.start()
    return "foo"
```

And I expect that whenever I access it in browser, I see "foo" immediately. 

However that's no the case. 

If I run 
```
sudo docker-compose up --no-start; sudo docker-compose run web bash
```

and one of these:

`flask run --host=0.0.0.0 --port=80`
`uwsgi --socket 0.0.0.0:80 --wsgi-file app/main.py --callable app --async --ugreen --protocol http`

then I see the response immediately, as expected. 

I tried all kind of configurations in uwsgi.ini:
```
[uwsgi]
module = app.main
callable = app
async
ugreen

[uwsgi]
module = app.main
callable = app
async = true
ugreen = true

[uwsgi]
module = app.main
callable = app
async = 100
```

added `processes`, `threads`, `enable_threads`. Nothing helps. 

Please help me...

**Comment by anurbol** [comment]
Is it related to supervisord?

**Comment by anurbol** [comment]
Thanks to this issue I got familiar with better alternatives like gunicorn, and FastAPI of the sane author, so I am currently migrating to them. This issue is, though not actual to me, probably should stay open

**Comment by tiangolo** [comment]
Hey @anurbol , if you are still having issues, please create a minimal self-contained example that I can run, that way I could help you. Otherwise, it's much more difficult.
