### ISSUE TITLE
Python 3 version

### ISSUE THREAD

**Issue by luckydonald** [tiangolo/uwsgi-nginx-flask-docker#2]
Could you provide a 3.5 python image?

**Comment by tiangolo** [comment]
Good point. I'll look into it.

**Comment by kootenpv** [comment]
That was the first thing I wondered as well.

**Comment by tiangolo** [comment]
Done :heavy_check_mark: :wink: 

There's now a Python 3.5 image tag for each Python 2.7 image tag.

Also, there's an example project template for each image tag.

You can pull the new images from [Docker Hub](https://hub.docker.com/r/tiangolo/uwsgi-nginx-flask/).

https://github.com/tiangolo/uwsgi-nginx-flask-docker/releases/tag/v0.2.0

It would be great if you could test them and let me know if everything worked OK before closing this issue.

**Comment by luckydonald** [comment]
I'll have a look at `flask-python3.5`

**Comment by kootenpv** [comment]
I am successfully using it :) Thanks!

**Comment by luckydonald** [comment]
Works here too

**Comment by tiangolo** [comment]
Great! :tada: Thanks for reporting back.
