### ISSUE TITLE
Issues running this container on Heroku: "unable to find user nginx"

### ISSUE THREAD

**Issue by misleadingTitle** [tiangolo/uwsgi-nginx-flask-docker#201]
I've tried without success to run this container in Heroku. It works fine on my machine (it's a classic) but when I push the image in Heroku it halts after the error in the title.

Here is the startup log (the user error is in the third to last line):

```
;uWSGI instance configuration
[uwsgi]
cheaper = 2
processes = 16
ini = uwsgi.ini
module = api.webapp
callable = app
uid = 1000
master = true
threads = 2
processes = 4
http-socket = :12851
ini = /etc/uwsgi/uwsgi.ini
socket = /tmp/uwsgi.sock
chown-socket = nginx:nginx
chmod-socket = 664
hook-master-start = unix_signal:15 gracefully_kill_them_all
need-app = true
die-on-term = true
show-config = true
;end of configuration

*** Starting uWSGI 2.0.18 (64bit) on [Wed Sep  9 10:12:42 2020] ***
compiled with version: 8.3.0 on 09 May 2020 21:28:19
os: Linux-4.4.0-1076-aws #80-Ubuntu SMP Thu Aug 6 06:48:10 UTC 2020
nodename: 433abee3-4997-407d-b0c0-f1196242ca3f
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /app
detected binary path: /usr/local/bin/uwsgi
your processes number limit is 256
your memory page size is 4096 bytes
detected max file descriptor number: 10000
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :12851 fd 3
unable to find user nginx
2020-09-09 10:12:42,407 INFO exited: uwsgi (exit status 1; not expected)
2020-09-09 10:12:43,408 INFO gave up: uwsgi entered FATAL state, too many start retries too quickly
```

I think the problem is related to the user because Heroku doesn't run images with root privileges. Do you think there is a workaround for this problem?

I've tried to replicate the same problem adding to my Dockerfile a non-root user with the following lines:

```
RUN useradd myuser 
USER myuser
```

When I run the image locally I'm getting a different error I think due to file writing privileges. I've tried to grant to `myuser` such permission but I don't think I'm going in the right direction.

Is there a way to use a non-root user to run this container?

PS: I don't think this is related to https://github.com/tiangolo/uwsgi-nginx-flask-docker/issues/188 because I've successfully managed to bind the port to the correct heroku env variable.

**Comment by GadWissberg** [comment]
@misleadingTitle Did you find a solution to that? I've been facing that too, can't find a solution anywhere...

**Comment by misleadingTitle** [comment]
Hi, unfortunately I gave up and used a different docker image that I've build starting from a vanilla Alpine and installed gunicorn (among other stuff)

**Comment by trydalch** [comment]
I'm having the same issue. Runs locally, can't find nginx user on heroku.

**Comment by tiangolo** [comment]
Hey, in the line with:

```
chown-socket = nginx:nginx
```

you are trying to set the configuration of the owner of the socket (like a file) to the user `nginx` and the group `nginx`, but you probably didn't create that user before.

---

On the other hand, I haven't used Heroku myself, but I suspect they would have some type of frontend proxy (Nginx, HAProxy, Traefik, or something else) on top of your app, probably handling HTTPS, etc. And I imagine it would probably handle starting more containers for your app if the number of your requests increases. In any of those cases, you would be better off *without* this image (or any other similar image) and instead, building from the official `python` image, installing Gunicorn, and running it with a single process.
