### ISSUE TITLE
Docker Compose Error on docker-compose.override.yml

### ISSUE THREAD

**Issue by sectsect** [tiangolo/uwsgi-nginx-flask-docker#202]
Hello.

I got an error on `docker-compose.override.yml`.
I suspect that the `build` option is missing.

```bash
# Rename files
$ mv docker-compose.yml docker-compose-prod.yml && mv docker-compose.override.yml docker-compose.yml
$ docker-compose up -d
ERROR: The Compose file is invalid because:
Service web has neither an image nor a build context specified. At least one must be provided.
```

https://github.com/tiangolo/uwsgi-nginx-flask-docker/blob/3835b6b0573c3adf8b4db73b440c81a814dae060/example-flask-python3.8/docker-compose.override.yml#L1-L14

```diff
version: '3'
services:
  web:
+   build: ./
    volumes:
      - ./app:/app
    ports:
      - "80:80"
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
      - 'RUN=flask run --host=0.0.0.0 --port=80'
    command: flask run --host=0.0.0.0 --port=80
    # Infinite loop, to keep it alive, for debugging
    # command: bash -c "while true; do echo 'sleeping...' && sleep 10; done"
```

Thanks.

**Comment by sectsect** [comment]
I didn't understand enough how to handle multiple Compose files.
https://docs.docker.com/compose/extends/

**Comment by tiangolo** [comment]
I imagine you solved your problem, thanks for coming back to close the issue! ☕ 

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
