### ISSUE TITLE
Unable to run image with modified PYTHONPATH

### ISSUE THREAD

**Issue by quoimec** [tiangolo/uwsgi-nginx-flask-docker#204]
Hello Tiangolo!

I have run into an issue with the PYTHONPATH environment variable that I am hoping you can shed some light on. In other generic python docker images, I have been installing pip packages to a specific directory and then using the PYTHONPATH value to make that directory a valid package location. When I tried to start doing this using the uwsgi-nginx-flask:python3.7 flask image however, I started running into problems.

At this point, I was running `ENV PYTHONPATH=/pip` in my docker image and was getting the following output when I tried to run the image: 
``` bash
Checking for script in /app/prestart.sh
Running script /app/prestart.sh
Running inside /app/prestart.sh, you could add migrations to this file, e.g.:

#! /usr/bin/env sh

# Let the DB start
sleep 10;
# Run migrations
alembic upgrade head

Traceback (most recent call last):
  File "/usr/bin/supervisord", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/pip/pkg_resources/__init__.py", line 1365
    raise SyntaxError(e) from e
                            ^
SyntaxError: invalid syntax
```

When I dug into your image however, I noticed that you were setting your own PYTHONPATH value, namely `ENV PYTHONPATH=/app`. When I removed my environment value setting, everything worked and UWSGI was able to load. To date I have tried setting the following environment values for python path in my Dockerfile but all of them have resulted in the same error message as above:
- `ENV PYTHONPATH=/app:/pip`
- `ENV PYTHONPATH=/pip:/app`
- `ENV PYTHONPATH=/pip:${PYTHONPATH}`
- `ENV PYTHONPATH=${PYTHONPATH}:/pip`

Any ideas? I have also tried moving my pip directory inside /app and adding /app/pip to the path but that fails to. In short, it just seems that any change the path what so ever results in an image failure.

**Comment by quoimec** [comment]
@tiangolo - any thoughts on this?

**Comment by tiangolo** [comment]
Hey! In theory, something like `ENV PYTHONPATH="/app:/pip"` should work.

But if it's not working in your case, please create a small `Dockerfile`, with a small minimal app code and dependencies so that I can try to replicate your issue locally, that way I could figure out what's happening.
