### ISSUE TITLE
Can't this image be made to run django?

### ISSUE THREAD

**Issue by nokemono** [tiangolo/uwsgi-nginx-flask-docker#207]
Can't this image be made to run django?

**Comment by tiangolo** [comment]
Yes, but you would probably use the parent image directly: https://github.com/tiangolo/uwsgi-nginx-docker

**Comment by nokemono** [comment]
for reference only.

uwsgi.ini
```
[uwsgi]
wsgi-file=/[django_app]/wsgi.py
module=[django_app].wsgi
```

[django_app]    Your django app name

**Comment by karlhedins** [comment]
Made a small example with [uwsgi-nginx-docker](https://github.com/tiangolo/uwsgi-nginx-docker) configured with Django:
https://github.com/karlhedins/uwsgi-nginx-django-docker
