### ISSUE TITLE
Plans to upgrade to python 3.9

### ISSUE THREAD

**Issue by CarstenKarbach** [tiangolo/uwsgi-nginx-flask-docker#209]
Do you plan for an upgrade to python 3.9?

**Comment by xokarekun** [comment]
python 3.9.2 was released

**Comment by ra9-dev** [comment]
Just bumping it to know if there's a plan for this?

**Comment by tiangolo** [comment]
Yep, I just did :tada:

You can use the new Python 3.9 version, check the updated docs: https://github.com/tiangolo/uwsgi-nginx-flask-docker

**Comment by xokarekun** [comment]
> 
> 
> Yep, I just did 🎉
> 
> You can use the new Python 3.9 version, check the updated docs: https://github.com/tiangolo/uwsgi-nginx-flask-docker

Thats realy cool, but yesterday was published [release candidate 2 to Python 3.10](https://www.python.org/downloads/release/python-3100rc2/)

**Comment by CarstenKarbach** [comment]
Thanks
