### ISSUE TITLE
Use of this container image with static files?

### ISSUE THREAD

**Issue by schmots1** [tiangolo/uwsgi-nginx-flask-docker#212]
I am using this image and 99% it does just what I want/need, however I can't get static files to read/load like css and images even though I have a static dir. what do I need to set to get this to work?

**Comment by schmots1** [comment]
Nevermind.. re-read the instructions again then looked at what I had done.. had a type in my Dockerfile

**Comment by tiangolo** [comment]
Thanks for reporting back and closing the issue 👍

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
