### ISSUE TITLE
Alpine example broken?

### ISSUE THREAD

**Issue by morganmcleod** [tiangolo/uwsgi-nginx-flask-docker#213]
I've been working with the python3.8-alpine.dockerfile example for a few weeks now and was getting close to having things set up for real development.   (I chose Alpine because I want to mount an SMB share and it seemed less painful than it was with Debian.)

Suddenly yesterday my container would exit right away upon launching.   The only log message is:

> ': No such file or directory

I reverted to the plain vanilla Dockerfile and prestart.sh from this repo and am still getting the same result.

Any ideas on how to troubleshoot this?

Using Docker Desktop Windows on Win10, latest everything, all updates applied.   I cleared Docker caches and images and rebuilt several times yesterday, all to the same result.

**Comment by tiangolo** [comment]
Hey, if you reverted to the vanilla `Dockerfile` (no Alpine) from this repo and you still have the same error, then it's probably not Alpine broken.

Try following the docs here again in a new project and see if that works. If it does, see what is different in the project from scratch and your own, you'll probably find the error somewhere there.

**Comment by morganmcleod** [comment]
I'll give it a try at some point.   I've kind of moved on from this project and no longer require SMB access.   Doing everything using FastAPI instead with no Docker involved yet.
