### ISSUE TITLE
Get "[Errno 13] Permission denied: " when uploading a file

### ISSUE THREAD

**Issue by GilKata** [tiangolo/uwsgi-nginx-flask-docker#215]
When I'm trying to upload a file, I get the error of permission denied: "[Errno 13] Permission denied: uploads/products.csv".
I tried to change the folder's chmod to 777 (which is not advisable), but still doesn't work.

What am I missing here?

Thanks!

Dockerfile:
```Dockerfile
FROM tiangolo/uwsgi-nginx-flask:python3.8-alpine

ENV UWSGI_INI /app/uwsgi.ini
ENV STATIC_URL /app/uploads
ENV LISTEN_PORT 5000
EXPOSE 5000

RUN apk add --update wget
RUN pip3 install --upgrade pip

COPY ./custom.conf /etc/nginx/conf.d/
COPY ./app /app
WORKDIR /app
RUN mkdir uploads
RUN chown -R root:root /app
RUN chmod 777 /app
RUN chmod 777 /app/uploads

RUN pip3 install --upgrade pip
RUN pip3 install -r ./requirements.txt
```

uwsgi.ini:
```uwsgi
[uwsgi]
module = main
callable = app
enable-threads = true
ignore-sigpipe = true
uid = nobody
gid = nobody
worker-reload-mercy = 300  
```

**Comment by tiangolo** [comment]
I imagine you solved your problem, thanks for reporting back and closing the issue 👍

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
