### ISSUE TITLE
Run as non root?

### ISSUE THREAD

**Issue by friday963** [tiangolo/uwsgi-nginx-flask-docker#217]
Hello,

I'm wondering if you have an advice, I've tried to deploy the uwsgi-nginx-flask container to Openshift, but because uwsgi runs as root it breaks the build and I ultimately cannot run this without getting admin assistance in allowing me to run a container as root. (Also it makes them mad that I'm running as root)   Is there a way to change the UID so I can run as an unprivileged user and if it is possible, is there any significant functionality I'll be lacking?

Thank you ,

Andrew

**Comment by eladavron** [comment]
Add `uid = nobody` in `uwsgi.ini` and it'll run as `nobody` which is non-root.
You can obviously choose any other `uid` of your choosing, but afaik `nobody` is the "recommended" non-root user to run servers as.

**Comment by friday963** [comment]
@eladavron  Thank you !  Just what I needed.

**Comment by tiangolo** [comment]
Thanks for the help here @eladavron ! 👏  🙇 

Thanks for reporting back and closing the issue @friday963  👍

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
