### ISSUE TITLE
Python 3.8 based image uses Python 3.7 packages when running apt-get install

### ISSUE THREAD

**Issue by lfleuren** [tiangolo/uwsgi-nginx-flask-docker#219]
After using the Python 3.7 images for a while we recently decided to upgrade our project to the 3.8 version. While initally everything was looking good, it appears that the new image does have a dependency with Python 3.7 althoug the default Python version in the container is Python 3.8.2.

In our dockerfile we begin installing addition packages using the follwing RUN command:

**RUN apt-get update && apt-get install -y python3-dev default-libmysqlclient-dev build-essential**

I would expect packages related to Python 3.8 would be upgraded. But this does not appear to be the case. The terminal output result after running this command is:

_Step 4/11 : RUN apt-get update && apt-get install -y python3-dev default-libmysqlclient-dev build-essential
 ---> Running in c199dff3a36f
Get:1 http://deb.debian.org/debian buster InRelease [122 kB]
Get:2 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
Get:3 http://deb.debian.org/debian buster-updates InRelease [51.9 kB]
Get:4 http://security.debian.org/debian-security buster/updates/main amd64 Packages [268 kB]
Get:5 http://deb.debian.org/debian buster/main amd64 Packages [7907 kB]
Get:6 http://deb.debian.org/debian buster-updates/main amd64 Packages [9504 B]
Fetched 8423 kB in 2s (4222 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
default-libmysqlclient-dev is already the newest version (1.0.5).
The following additional packages will be installed:
  dh-python libpython3-dev libpython3.7 libpython3.7-dev libpython3.7-minimal
  libpython3.7-stdlib python3.7 python3.7-dev python3.7-minimal
Suggested packages:
  python3.7-venv python3.7-doc binfmt-support
The following NEW packages will be installed:
  build-essential dh-python libpython3-dev libpython3.7 libpython3.7-dev
  python3-dev python3.7-dev
The following packages will be upgraded:
  libpython3.7-minimal libpython3.7-stdlib python3.7 python3.7-minimal
4 upgraded, 7 newly installed, 0 to remove and 89 not upgraded.
Need to get 54.9 MB of archives.
After this operation, 89.4 MB of additional disk space will be used._

Somehow it installs Python 3.7 related packages, resulting in obvious problems when running our build steps.

Any idea how to solve this?

**Comment by tiangolo** [comment]
If you install with `apt` that will use the default Python version repackaged by Debian. You are probably better off installing with `pip`.
