### ISSUE TITLE
support python 3.7 and alpine 3.12

### ISSUE THREAD

**Issue by liranbenabu1** [tiangolo/uwsgi-nginx-flask-docker#221]
Hi, 
it's an amazing project. 
thanks a lot. 
today we're using python 3.7 on alpine 3.8. 
we would like to upgrade the OS system to alpine 3.12. 
can you please such a version ? 

thanks again

**Comment by tiangolo** [comment]
Hello! Sorry for the delay. I no longer support Alpine tags and I wouldn't recommend them. You can read more about it here: https://github.com/tiangolo/uwsgi-nginx-flask-docker#-alpine-python-warning

Given that, I'll close this one. :coffee:
