### ISSUE TITLE
Unable to run in Openshift

### ISSUE THREAD

**Issue by peterkohaut** [tiangolo/uwsgi-nginx-flask-docker#29]
Container can not run in openshift because its trying to write to /etc/nginx/. Containers in Openshift (by default) are not running as root nor they can't get root access.

**Comment by tiangolo** [comment]
Interesting. How would you run an official Nginx image with custom configurations then? https://hub.docker.com/_/nginx/

**Comment by peterkohaut** [comment]
I'm not using that, so I can't tell. But if there are changes needed in /etc I would say, it is better to do them in the dockerfile instead of entrypoint.sh, like chmod a+w /etc/nginx/conf.d/ in dockerfile or reading  config from /tmp or other writable path.

**Comment by tiangolo** [comment]
How having it in the `Dockerfile` would improve things if it would need to be run by a root user at build time?

Do you have any official reference from OpenShift explaining all that?

**Comment by peterkohaut** [comment]
Ah sorry, I explained myself badly, when building image you can use root. Only at run time you are not allowed to run them as root.

**Comment by tiangolo** [comment]
I see. Do you have any reference to the OpenShift docs explaining all that?

**Comment by peterkohaut** [comment]
it's mentioned here: https://blog.openshift.com/getting-any-docker-image-running-in-your-own-openshift-cluster/

**Comment by peterkohaut** [comment]
Thanks! I ended up writing very similar dockerfile just after reporting this issue. But it would be nice to this have this mentioned in documentation.

**Comment by tiangolo** [comment]
@peterkohaut would you mind sharing with us how you built your image?

**Comment by peterkohaut** [comment]
I wrote my own simple dockerfile without nginx ant it is based on "python" image and entrypoint is just ENTRYPOINT ["uwsgi", "--http", "0.0.0.0:8000", "--module", "main:app", "--processes", "1", "--threads", "8"]
it is not very effective but works fine for my needs

**Comment by tiangolo** [comment]
Thanks @peterkohaut !

**Comment by amos-baron** [comment]
@tiangolo after using the dockerfile you suggested im getting 


`
2020/08/03 12:11:37 [emerg] 15#15: bind() to 0.0.0.0:80 failed (98: Address already in use)
`

**Comment by tiangolo** [comment]
@amos-baron are you running `ss` inside the container or outside? If outside, then there would be something else already listening on port 80. Maybe an older container.

**Comment by berndkuennen** [comment]
I found two ways to get it running on Openshift. One is to let it run with a _serviceAccount_ which is granted the "anyuid" policy. 

The other one is to use the fact that in OCP the pod still runs with _gid=0_. This needs some small enhancements, though. You need to move the port to above 1023 and change some config files, too.

Find details about both solutions in my article at https://github.com/berndkuennen/lint_trilogy/blob/master/tiangolo/Readme.md .
