### ISSUE TITLE
All static files return 403

### ISSUE THREAD

**Issue by Garulf** [tiangolo/uwsgi-nginx-flask-docker#297]
Not sure what I'm doing wrong but all my static files are issuing `403` errors and `permission denied` errors.

Logging into the docker environment and changing permissions to 777 fixes the errors but doesn't fix the underlying issue.

**Comment by iamjackg** [comment]
Looks like the nginx workers run as the `nginx` user, so unless your static files are readable by everybody (and your folders readable and executable by everybody) you're gonna get permissions errors.
