### ISSUE TITLE
net::ERR_INCOMPLETE_CHUNKED_ENCODING

### ISSUE THREAD

**Issue by mbernico** [tiangolo/uwsgi-nginx-flask-docker#30]
I have a jquery front end that is trying to send images to an app inside the uwsgi-nginx-flask-docker container.

The javascript console is saying this:
jquery.min.js:4 POST http://localhost:8000/predict/ net::ERR_INCOMPLETE_CHUNKED_ENCODING

If I use the same app with only gunicorn it works ok, so I'm suspecting this is related to nginix configuration inside the container?

more Dockerfile
FROM tiangolo/uwsgi-nginx-flask:python3.6

COPY ./app /app

RUN pip install -r requirements.txt

On the client side I'm using this plugin to submit the form using ajax  http://malsup.com/jquery/form/

**Comment by tiangolo** [comment]
Check what the log in your Docker container is saying.

```
docker logs my-container
```

Also try the advanced instructions to discard Nginx and see if that's what is creating the actual problem: https://github.com/tiangolo/uwsgi-nginx-flask-docker#more-advanced-development-instructions

**Comment by tiangolo** [comment]
As this issue is a bit old, I'll assume your problem was solved and close it.
