### ISSUE TITLE
Logging problems

### ISSUE THREAD

**Issue by mcuervoe** [tiangolo/uwsgi-nginx-flask-docker#32]
Hi tiangolo,

I am having problems logging messages when I used the uwsgi-nginx-flask image. The application works.   I am only having issues with the logging. On the other hand, If I run the app in standalone, everything, including logging, works as expected.

I tried to look for info on how to configure the logging mechanism when using uwsgi-nginx-flask, but I was not able to find anything.

Let me explain the scenario.

I am using uwsgi-nginx-flask:python3.6 to run a flask app. 

My uwsgi.ini is
```
[uwsgi]
module = iedapp.app
callable = app
logger = python
```

The app is using resources for handling request.  

```
....
app = Flask(__name__, static_folder=None)
app.config.from_object(config)
api = Api(app, prefix='/api', base_path='/api', api_version='1.0')
api.add_resource(IedOnline, '/online/<string:ied_key>/<string:layout>')
....
```

And in the resource, I have something like
```
....
logger = logging.getLogger('test')

class IedOnline(Resource):
    def post(self, ied_key, layout):
         print("Hello!!!")
         current_app.logger.error("Hello again!!!!")
         logger.error("Hello again and again")
....
```
What happens to me is that both the print and logging messages in the resource function get lost. I am not able to find them either in the docker logs not if I exec into the docker image and look for entries in all the *.log files in the image.

Could you provide guidance on what I should be going wrong?

**Comment by tiangolo** [comment]
It seems to be related to your code.

First, you shouldn't need to add `logger = python` to your `uwsgi.ini`.

Then, inside a normal Flask endpoint I ran a `print('--------------------print')` and it appeared in the Docker container logs.

Then I tried importing `logging`:

`import logging`

And then logging an error:

`logging.error('----------------eeeerrrr')`

And it also worked. The error log was in the output of the Docker container:

```
...

2018-01-09 17:18:12,883 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-01-09 17:18:12,883 INFO success: uwsgi entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
ERROR:root:----------------eeeerrrr
--------------------print
[pid: 5020|app: 0|req: 1/1] 172.21.0.4 () {60 vars in 1445 bytes} [Tue Jan  9 17:18:23 2018] POST /api/v2/login/test-token => generated 605 bytes in 137 msecs (HTTP/1.1 200) 5 headers in 195 bytes (2 switches on core 0)
172.21.0.4 - - [09/Jan/2018:17:18:23 +0000] "POST /api/v2/login/test-token HTTP/1.1" 200 605 "http://dev.example.com/swagger/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36" "172.21.0.1"

...
```

So, it seems it might be a problem in how you are defining your logging, your endpoint or the framework you are using (maybe Flask-Rest or Flask-Restplus).

---

Just as a side note, after researching and trying several Flask API frameworks, I'm very happily using Flask-apispec. You might want to check out this project generator, using it (with several other features): https://github.com/senseta-os/senseta-base-project

**Comment by tiangolo** [comment]
Did you solve your problem? May we close this issue?

**Comment by tiangolo** [comment]
Cool, thanks for reporting back.
