### ISSUE TITLE
Add prefix to flask application URLs

### ISSUE THREAD

**Issue by automactic** [tiangolo/uwsgi-nginx-flask-docker#34]
I am wondering if you would consider allow users of this docker image to be able to set their own prefix of the flask application. For example, I would like to do something like this:

- `location \` served directly from a directory, not just `index.html`
- `location \api` served by flask app

Or better yet, allow users to use their own `nginx.conf`. We could do this by checking if a `nginx.conf` file already exists before generating one in `entrypoint.sh`.

Thanks!

**Comment by tiangolo** [comment]
If it's a directory without an `index.html`, what would it serve?

A web server doesn't have a way to "serve" a directory. That's not specific to this project, is how the web works. 

Maybe you refer to serving a simple web page with links to specific files inside the directory?

That's what Apache (not Nginx) does in some cases, but still, it actually generates some kind of an "`index.html`" on the fly.

---

Of course, you can add custom Nginx configs additional to the first one. Check out the corresponding documentation in the README: https://github.com/tiangolo/uwsgi-nginx-flask-docker#customizing-nginx-configurations

**Comment by automactic** [comment]
Ah, yes, I guess this is kind of pointless and out of scope of this project. 

I have a Angular frontend. When you build the Angular app, it generates javascript in the same directory of `index.html`. I'd have to return index.html instead of 404 for URLs not found. That would be too complicated.

Thanks for the suggestion regarding custom nginx config, I will try it out.

**Comment by tiangolo** [comment]
Ah, OK, in that case, you might want to check the section of the documentation dedicated specifically to how to add an Angular application to the same image: https://github.com/tiangolo/uwsgi-nginx-flask-docker#quickstart-for-spas
