### ISSUE TITLE
cannot use custom uwsgi.ini in flask app

### ISSUE THREAD

**Issue by higee** [tiangolo/uwsgi-nginx-flask-docker#37]
Hi tiangolo!

I've been working around with your docker image to deploy my python application.
Things were fine until I tried customizing `uwsgi.ini` file.

First of all, following is my flask project architecture.

<img width="227" alt="screen shot 2018-02-07 at 4 45 49 pm" src="https://user-images.githubusercontent.com/16909821/35904426-69012536-0c26-11e8-9ff7-632aace3becf.png">

Inside my `Dockerfile` includes following lines.

```
FROM tiangolo/uwsgi-nginx-flask:python3.6
COPY ./app /app
COPY ./app/conf/nginx.conf /etc/nginx/
COPY ./uwsgi.ini /app/uwsgi.ini
COPY ./requirements.txt /app/
RUN pip install -r /app/requirements.txt
ENV UWSGI_INI /app/uwsgi.ini
```

and I also tried with following `Dockerfile`.

```
FROM tiangolo/uwsgi-nginx-flask:python3.6
COPY ./app /app
COPY ./app/conf/nginx.conf /etc/nginx/
COPY ./uwsgi.ini /app/uwsgi.ini
COPY ./requirements.txt /app/
RUN pip install -r /app/requirements.txt
ENV UWSGI_INI /app/uwsgi.ini
WORKDIR /app
```

My custom `uwsgi.ini` is as follows.

```
[uwsgi]
module = main
callable = app
lazy-apps = true
processes = 1
```

If I run a docker container with above image, I see following logs.

<img width="1066" alt="screen shot 2018-02-07 at 4 57 35 pm" src="https://user-images.githubusercontent.com/16909821/35904846-0a108358-0c28-11e8-9aaf-aa9503ac0c87.png">

Thanks in advance!

**Comment by tiangolo** [comment]
Here's how uWSGI is configured, from the base image: https://github.com/tiangolo/uwsgi-nginx-docker

> 2016-08-16: Use dynamic a number of worker processes for uWSGI, from 2 to 16 depending on load. This should work for most cases. This helps especially when there are some responses that are slow and take some time to be generated, this change allows all the other responses to keep fast (in a new process) without having to wait for the first (slow) one to finish.

---

Now, what are you trying to achieve exactly? What do you want the `lazy-apps` for?

**Comment by higee** [comment]
[Here's my issue in detail](https://github.com/dcrosta/flask-pymongo/issues/101). Bottom line is that I'm saving data to mongodb using flask-pymongo but flask-pymongo gives me a warning that says:
```
MongoClient opened before fore. Create MongoClient only after forking. 
See PyMongo's documentation for details: http://api.mongodb.org/python/current/faq.html#is-pymongo-fork-safe
```

So while searching a way to solve this, I found [this issue](https://github.com/dcrosta/flask-pymongo/issues/66) in flask-pymongo repository. In the middle of the thread, there is a comment from hut8 that says:

---
@dkiser Out of curiosity, what app server are you using? I am using uwsgi. I just spent like two hours with a bug that I think is the same. Mine never throws an exception but instead just hangs, and this is what I get in the logs.

```
announcing my loyalty to the Emperor...
/srv/venv/lib/python3.4/site-packages/pymongo/topology.py:74: UserWarning: MongoClient opened before fork. Create MongoClient with connect=False, or create client after forking. See PyMongo's documentation for details: http://api.mongodb.org/python/current/faq.html#using-pymongo-with-multiprocessing>
  "MongoClient opened before fork. Create MongoClient "
[pid: 15145|app: 0|req: 1/2]  1.2.3.4 () {46 vars in 753 bytes} [Sun Jan 24 01:54:21 2016] GET /stats => generated 39 bytes in 30023 msecs (HTTP/1.1 500) 2 headers in 90 bytes (1 switches on core 0)
There's a timeout at 30 seconds. I can connect just fine using exactly the same stack/virtualenv (minus the app server of course) using a Flask-Script shell (https://flask-script.readthedocs.org/en/latest/#shell).
```
My solution was a one line fix; just add lazy-apps = true to my uwsgi INI file. That makes the workers fork then load the application.

---

So I was trying to test his idea of setting `lazy-apps=true` inside `uwsgi.ini`.
Following is some blocks of code to help you grasp what I was trying to do.

#### main.py

```
from flask import Flask
from flask_restful import Api
from flask_pymongo import PyMongo
from resources.test import Test

app = Flask(__name__)
app.config['MONGO_DBNAME'] = ''
app.config['MONGO_URI'] = ''
app.mongo = Pymongo(app, config_prefix='MONGO')

api = Api(app)
api.add_resource(Test, '/test')

if __name__ == '__main__':
    app.run(port=7000)
```

#### resources/test.py

```
from flask_restful import Resource, reqparse
from flask import current_app
 
class User(Resource):
 
    parser = reqparse.RequestParser()
 
    parser.add_argument('name', type=str)
    parser.add_argument('age', type=int)
 
    def post(self):
 
        data = User.parser.parse_args() 
        response  = {
            'name' : data['name'], 
            'age' : data['age']
        }
 
        current_app.mongo.db.test_collection.insert_one(response)        
 
        return {'message' : 'successfully inserted'}
```

**Comment by higee** [comment]
I changed my code a bit and it gives me the same warning only once.
So I guess I no longer have to change `uwsgi.ini` for this issue.

#### main.py

```
from flask import Flask
from flask_restful import Api
from flask_pymongo import PyMongo

app = Flask(__name__)
app.config['MONGO_DBNAME'] = ''
app.config['MONGO_URI'] = ''
app.mongo = Pymongo(app, config_prefix='MONGO')

from resources.test import Test

api = Api(app)
api.add_resource(Test, '/test')

if __name__ == '__main__':
    app.run(port=7000)
```

#### resources/test.py

```
from flask_restful import Resource, reqparse
from main import mongo
 
class Test(Resource):
 
    parser = reqparse.RequestParser()
 
    parser.add_argument('name', type=str)
    parser.add_argument('age', type=int)
 
    def post(self):
 
        data = Test.parser.parse_args() 
        response  = {
            'name' : data['name'], 
            'age' : data['age']
        }
 
        mongo.db.test_collection.insert_one(response)        
 
        return {'message' : 'successfully inserted'}
```

**Comment by tiangolo** [comment]
Cool! It seems you solved your issue. :tada: 

---

If by any chance you need to modify and debug it more, it might help you to know that this image bases itself on another image with just `uwsgi-nginx` and it has two `uwsgi.ini` files at the same time. To allow having a general one with all the default configurations and another one with the specific app configuration, without all the noise, to ease development.

Here's where the first file is copied in the `Dockerfile`: https://github.com/tiangolo/uwsgi-nginx-docker/blob/master/python3.6/Dockerfile#L110

Here's where the second file is copied in the `Dockerfile`: https://github.com/tiangolo/uwsgi-nginx-docker/blob/master/python3.6/Dockerfile#L142

Here's the first (default, global) `uwsgi.ini` file: https://github.com/tiangolo/uwsgi-nginx-docker/blob/master/python3.6/uwsgi.ini

Here's the original base app specific `uwsgi.ini`: https://github.com/tiangolo/uwsgi-nginx-docker/blob/master/python3.6/app/uwsgi.ini

This image replaces that base app specific `uwsgi.ini` with: https://github.com/tiangolo/uwsgi-nginx-flask-docker/blob/master/python3.6/app/uwsgi.ini

**Comment by higee** [comment]
Thanks for the comment!!  I'll go over the links you've attached! And since I'm done with this specific issue, I think it's better to close it.

**Comment by Thx3r** [comment]
If it can help, I solved by replace :  

`from flask.ext.mongoengine import MongoEngine`

by : 

`from flask_mongoengine import MongoEngine`
