### ISSUE TITLE
Cannot update server block in nginx.conf

### ISSUE THREAD

**Issue by chris-infospace** [tiangolo/uwsgi-nginx-flask-docker#39]
Due to the way that the external nginx configs are included into the root nginx.conf file, it's not possible to change the primary server block, which is something I need.

As a work around, we manually update the file to include various lines, but this isn't clean and it would be nicer to just put nginx configs into a folder somewhere and have them included automatically.

**Comment by tiangolo** [comment]
> ...put nginx configs into a folder somewhere and have them included automatically.

What do you mean by that? 

Like the `/etc/nginx/conf.d/` directory? 

That directory works as normal, the Nginx section of this image is, as much as possible, just a copy of the official Nginx image. 

Check that official documentation: https://hub.docker.com/_/nginx/

You can add additional custom Nginx configs in a `Dockerfile` with something like:

```Dockerfile
...

COPY custom-app-nginx-configs.conf /etc/nginx/conf.d/

...
```

---

If additional Nginx configs don't solve your problem because you definitely need to change the main Nginx file, you can create an `entrypoint.sh`, you can start from a copy of the one in this image, modify it to your needs and put it in your `Dockerfile`.

**Comment by chris-infospace** [comment]
Ok, that's what we've done so far. We need to create an additional location block in the server block generated in entrypoint.sh, I had maintenance concerns about modifying this particular .sh file to do so. It would be nicer to not have to do this, but if it's likely to never change then I'm ok with that solution.

**Comment by tiangolo** [comment]
I see. The entrypoint writing the Nginx file is there to support some environment variables that modify the Nginx configuration, like: https://github.com/tiangolo/uwsgi-nginx-flask-docker#custom-listen-port

One option would be to maintain your own `entrypoint.sh`.

Another option would be to create a pull request solving it, for example, in the `entrypoint.sh`, reading some file in some determined location and injecting it in the Nginx config (like with the configuration env vars).

**Comment by chris-infospace** [comment]
Yeah, that makes sense. As of right now, here is what I've done:
* override the `entrypoint.sh` file, and just have it echo out "ran entrypoint.sh, but didn't do anything".
* add my own `nginx.conf` for my app
* copy it in via the `Dockerfile`

That works better for our needs. I would be open to the idea of an environment variable that points to a file, and if it exists copy that over instead of building the one in `entrypoint.sh`. I may open a PR for that. For reference, here is the `nginx.conf` file we're using:
```
client_max_body_size 0;

gzip on;
gzip_types *;

server {
    listen 5050;

    location / {
        try_files \$uri @app;
    }
    location @app {
        include uwsgi_params;
        uwsgi_pass unix:///tmp/uwsgi.sock;
    }

    location /robots.txt {
        alias /app/app/static/site-data/robots.txt;
    }
    location /sitemap.xml {
        alias /app/app/static/site-data/sitemap.xml;
    }
    location /static {
        alias /app/app/static;
    }
}
```

**Comment by tiangolo** [comment]
Cool! Thanks for sharing it. Should we close this issue now then?

**Comment by chris-infospace** [comment]
Yeah, we can close this issue.
