### ISSUE TITLE
ssl integration

### ISSUE THREAD

**Issue by franc01s** [tiangolo/uwsgi-nginx-flask-docker#42]
I'm looking for a way to smoothly integrate ssl certificates through nginx config.
Any clues will be appreciated.

**Comment by tiangolo** [comment]
This is becoming a recurrent subject, I'll try to add some info in the README.

Long story short, use [Traefik](https://traefik.io/) as a [TLS termination proxy](https://en.wikipedia.org/wiki/TLS_termination_proxy).

Here's a project generator that includes that and more stuff. You can generate one project in seconds and see the file structure.

**Comment by franc01s** [comment]
Hi Thank you for the info.
For the moment, I did 

ENV LISTEN_PORT ‘443 ssl’
EXPOSE 443

and put certificates in NGINX .conf file copies in Dockerfile

**Comment by tiangolo** [comment]
Oops! I see I didn't post the link to the project generator with Traefik and TLS  certificate genration: https://github.com/tiangolo/full-stack

Anyway, I'm glad you solved your problem.
