### ISSUE TITLE
Too many “SIGPIPE: writing to a closed pipe/socket/fd” error for every seconds, on Flask + Nginx

### ISSUE THREAD

**Issue by yccheok** [tiangolo/uwsgi-nginx-flask-docker#44]
Currently, I have the following simple Flask + Nginx web application.

Dockerfile
----------

    FROM tiangolo/uwsgi-nginx-flask:python3.6-alpine3.7
    
    
    # Install the required packages
    RUN pip install celery
    
    
    COPY . /app

main.py
-------

    import json
    import os
    from flask import Flask, request
    from flask import url_for
    from celery import Celery
    from celery.result import AsyncResult
    import celery.states as states
    import constants
    import logging
    
    
    app = Flask(__name__)
    
    
    @app.route('/stock_price_alert', methods = ['POST'])
    def stock_price_alert():
        request_data = request.get_json()
    
        if not request_data:
            return 'empty_data'
    
        celery = Celery('stock_price_alert', broker=constants.CELERY_BROKER_URL, backend=constants.CELERY_RESULT_BACKEND)
        celery.send_task('stock_price_alert.run', queue='stock_price_alert', args=[request_data], kwargs={})
        return 'stock_price_alert'
    
    
    if __name__ == '__main__':
        app.run(debug=env.get('DEBUG',True),
                port=int(env.get('PORT',5000)),
                host=env.get('HOST','0.0.0.0')
        )

I have another node.js app, which will perform POST to `/stock_price_alert`, like every 10 seconds.

    function post_stock_price_to_flask(json) {
        var options = {
          uri: 'http://flask/stock_price_alert',
          method: 'POST',
          json: json
        };
        
        request(options, function (error, response, body) {
        });

Things work pretty OK for few hours, till my CPU suddenly spike up.

[![enter image description here][1]][1]

Then, I keep receiving the error log, if I perform `docker-compose logs flask`

    flask_1                            | Mon Feb 26 19:44:55 2018 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /stock_price_alert (ip 172.18.0.8) !!!
    flask_1                            | Mon Feb 26 19:44:55 2018 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /stock_price_alert (ip 172.18.0.8) !!!
    flask_1                            | Mon Feb 26 19:44:55 2018 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /stock_price_alert (ip 172.18.0.8) !!!
    flask_1                            | Mon Feb 26 19:44:55 2018 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /stock_price_alert (ip 172.18.0.8) !!!
    flask_1                            | Mon Feb 26 19:44:55 2018 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /stock_price_alert (ip 172.18.0.8) !!!
    flask_1                            | Mon Feb 26 19:44:55 2018 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /stock_price_alert (ip 172.18.0.8) !!!
    flask_1                            | Mon Feb 26 19:44:55 2018 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /stock_price_alert (ip 172.18.0.8) !!!
    flask_1                            | Mon Feb 26 19:44:55 2018 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /stock_price_alert (ip 172.18.0.8) !!!
    flask_1                            | Mon Feb 26 19:44:55 2018 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /stock_price_alert (ip 172.18.0.8) !!!
    flask_1                            | Mon Feb 26 19:44:55 2018 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /stock_price_alert (ip 172.18.0.8) !!!
    flask_1                            | Mon Feb 26 19:44:55 2018 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /stock_price_alert (ip 172.18.0.8) !!!
    flask_1                            | Mon Feb 26 19:44:55 2018 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /stock_price_alert (ip 172.18.0.8) !!!
    flask_1                            | Mon Feb 26 19:44:55 2018 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /stock_price_alert (ip 172.18.0.8) !!!
    flask_1                            | Mon Feb 26 19:44:56 2018 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /stock_price_alert (ip 172.18.0.8) !!!

I even shutdown the node.js app, to ensure no one is sending POST to `/stock_price_alert`

Still, after I shutdown my node.js, Flask still keep generating the error log, and the CPU usage still very high.

May I know is there any other thing I can debug?

p/s Here's my docker stats output

    CONTAINER ID        NAME                                                   CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
    357b5cd5c472        jstocknotification_flask_1                             56.18%              127.7MiB / 992.3MiB   12.87%              267MB / 220MB       94.7GB / 4.1kB      8

  [1]: https://i.stack.imgur.com/lLjG8.png

**Comment by tiangolo** [comment]
Well, this line: `celery = Celery('stock_price_alert', broker=constants.CELERY_BROKER_URL, backend=constants.CELERY_RESULT_BACKEND)` should probably be outside of your route.

Otherwise, you are creating a new Celery app every time you receive a request. I would try that first.

If you want to check how a project with Celery already configured could look like, check this one (it uses this same image): https://github.com/senseta-os/senseta-base-project

**Comment by yccheok** [comment]
Thanks for advice. After moving `celery = Celery('stock_price_alert', broker=constants.CELERY_BROKER_URL, backend=constants.CELERY_RESULT_BACKEND)` outside function scope, the performance of the server is much more predictable, and having much less spike.

However, I'm not exactly sure whether this is the root cause of the problem. Because at the same time, we had migrated to `gunicorn`, due to its simplicity.

**Comment by tiangolo** [comment]
I'm glad you solved your problem.
