### ISSUE TITLE
Invalid checksum for python3.6

### ISSUE THREAD

**Issue by jesal-xad** [tiangolo/uwsgi-nginx-flask-docker#45]
Looks like the checksum is invalid for one of the layers in `python3.6` causing pull failure:
```
➜  ~ docker pull tiangolo/uwsgi-nginx:python3.6
python3.6: Pulling from tiangolo/uwsgi-nginx
723254a2c089: Pull complete
abe15a44e12f: Pull complete
409a28e3cc3d: Pull complete
503166935590: Pull complete
0f46f97746e4: Verifying Checksum
fe27feb3d509: Download complete
5efd1be29fdb: Download complete
1c7f21b2c7a5: Download complete
19d6f0b88217: Download complete
9bc015449d3b: Download complete
bc6664ce3000: Download complete
5637fc6942bc: Download complete
3e8e08378b8c: Download complete
9ee4941c6912: Download complete
68dc3e6ae1ee: Download complete
c99e37b352fe: Download complete
951c675c83e3: Download complete
d70540e3752a: Download complete
7e38e9f9b2d7: Download complete
a9852b3eea18: Download complete
97deda0086e7: Download complete
filesystem layer verification failed for digest sha256:0f46f97746e4df5959e8c821ca69fdd6c0bedd611c1e0ab3b6970f7202b9bb10
➜  ~
```
I was able to successfully pull from `python3.6-alpine3.7` as well as `python3.5`.

**Comment by tiangolo** [comment]
I just tried and it worked normally. Can you try again? 

Or maybe from a different server in a different location?

It can be a problem related to your ISP, internal firewall, national firewall, etc.

**Comment by tiangolo** [comment]
Given the lack of additional comments in some time, I'll assume you solved your problem and close this issue. But feel free to post more comments here if you want to re-open it or continue the conversation.
