### ISSUE TITLE
Environment variable NGINX_WORKER_PROCESSES not implemented

### ISSUE THREAD

**Issue by jer0nim0** [tiangolo/uwsgi-nginx-flask-docker#47]
Documentation says NGINX_WORKER_PROCESSES can be configured, but it appears it is not actually implemented in uwsgi-nginx-flask-docker. I think you have to merge the following commit (from uwsgi-nginx-docker) with this repo as well.
https://github.com/tiangolo/uwsgi-nginx-docker/commit/6bda98b73404e9a277abefc481402b556656c095

**Comment by tiangolo** [comment]
Sorry for the delay!

It's in the latest commit. The Docker images are being built with those changes right now: https://hub.docker.com/r/tiangolo/uwsgi-nginx-flask/builds/

**Comment by tiangolo** [comment]
Given the lack of additional comments in some time, I'll assume you solved your problem and close this issue. But feel free to post more comments here if you want to re-open it or continue the conversation.
