### ISSUE TITLE
ggc breaks nginx?

### ISSUE THREAD

**Issue by usmcamp0811** [tiangolo/uwsgi-nginx-flask-docker#49]
I am trying to use `tiangolo/uwsgi-nginx-flask:python3.6` as a base image so that I can build a Docker for my Flask WebApp. I have a Kerberos and MS SQL Server dependency. I have been racking my brain trying to get this to work for awhile. I think the problem is with `gcc`. I couldn't figure out what was wrong for a while and finally just started off adding one program at a time. I didn't get too far till I got the error below. 
```
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
Python version: 3.6.4 (default, Dec 21 2017, 01:29:34)  [GCC 6.3.0 20170516]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x5558e0f37f70
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 1237056 bytes (1208 KB) for 16 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x5558e0f37f70 pid: 9 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 9)
spawned uWSGI worker 1 (pid: 11, cores: 1)
spawned uWSGI worker 2 (pid: 12, cores: 1)
2018-04-06 21:21:04,343 INFO spawned: 'nginx' with pid 13
2018-04-06 21:21:04,343 INFO success: uwsgi entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018/04/06 21:21:04 [emerg] 13#13: open() "/etc/nginx/conf.d/default.conf" failed (2: No such file or directory) in /etc/nginx/nginx.conf:31
nginx: [emerg] open() "/etc/nginx/conf.d/default.conf" failed (2: No such file or directory) in /etc/nginx/nginx.conf:31
2018-04-06 21:21:04,361 INFO exited: nginx (exit status 1; not expected)
2018-04-06 21:21:06,366 INFO spawned: 'nginx' with pid 14
2018/04/06 21:21:06 [emerg] 14#14: open() "/etc/nginx/conf.d/default.conf" failed (2: No such file or directory) in /etc/nginx/nginx.conf:31
nginx: [emerg] open() "/etc/nginx/conf.d/default.conf" failed (2: No such file or directory) in /etc/nginx/nginx.conf:31
2018-04-06 21:21:06,384 INFO exited: nginx (exit status 1; not expected)
2018-04-06 21:21:09,391 INFO spawned: 'nginx' with pid 15
2018/04/06 21:21:09 [emerg] 15#15: open() "/etc/nginx/conf.d/default.conf" failed (2: No such file or directory) in /etc/nginx/nginx.conf:31
nginx: [emerg] open() "/etc/nginx/conf.d/default.conf" failed (2: No such file or directory) in /etc/nginx/nginx.conf:31
2018-04-06 21:21:09,409 INFO exited: nginx (exit status 1; not expected)
2018-04-06 21:21:10,409 INFO gave up: nginx entered FATAL state, too many start retries too `quickly`
```

My Dockerfile that made this looks like:

```
FROM tiangolo/uwsgi-nginx-flask:python3.6

RUN echo "deb http://ftp.us.debian.org/debian unstable main contrib non-free" > /etc/apt/sources.list.d/unstable.list
RUN cat /etc/*-release

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get -qq update && apt-get -y install libopendbx1-mssql curl apt-transport-https

RUN apt-get -y install gcc

###############################################################
# Copy over Kerberos config files
###############################################################
COPY ./krb5.conf /etc/krb5.conf
COPY ./common-session /etc/pam.d/common-session
COPY ./webapp.keytab /etc/krb5.keytab

COPY ./app /app
```

**Comment by tiangolo** [comment]
I don't think `gcc` is related. Check the error logs, specifically:

```
2018/04/06 21:21:04 [emerg] 13#13: open() "/etc/nginx/conf.d/default.conf" failed (2: No such file or directory) in /etc/nginx/nginx.conf:31
```

It seems like somehow your Nginx is trying to open a file that doesn't exists, because it is removed in the base image here: https://github.com/tiangolo/uwsgi-nginx-docker/blob/master/python3.6/Dockerfile#L106

But Nginx only tries to open files that exist in that directory. Are you sure you don't have a volume mounted there or something similar?

**Comment by usmcamp0811** [comment]
I'm still really new to Nginx.. which config file tells Nginx to try and open the `default.conf` file? 

No volumes.. I just do `docker run -it --name mysitename -p80:80 -p443:443 theimagename` 

I've tried installing Kerberos and SQL Server drivers after starting the container and as soon as the container restarts something gets changed and things don't work.

**Comment by tiangolo** [comment]
Can you set up a repo that I can check, run, and see the error?

I will probably be able to help you more easily by seeing your full environment, configurations, etc, directly.

**Comment by jackadam1981** [comment]
try pip freeze ,get requirements.txt

in dockerfile 
copy requiremints.txt to docker
RUN  pip install -r /app/app/requirements.txt

it can help you install SQL Server drivers in docker at built time.

**Comment by tiangolo** [comment]
Given the lack of additional comments in some time, I'll assume you solved your problem and close this issue. But feel free to post more comments here if you want to re-open it or continue the conversation.

**Comment by 5t33** [comment]
just ran into this again. Requirements.txt is:
