### ISSUE TITLE
Add ELK Elasticsearch to this template

### ISSUE THREAD

**Issue by springrid** [tiangolo/uwsgi-nginx-flask-docker#50]
Struggeling to find a good setup with ELK to monitor a flask api backend. I want to log all api requests and maybe certain things within the flask app. Would be awesome if this could be included here!

**Comment by tiangolo** [comment]
I think you want to use an Elastic "APM" (Application Performance Monitoring) https://www.elastic.co/solutions/apm. 

There is a Python agent that you can install in your Flask application: https://www.elastic.co/guide/en/apm/agent/python/current/getting-started.html

Actually, it has direct integration with Flask, apparently: https://www.elastic.co/guide/en/apm/agent/python/current/flask-support.html

---

I have used ElasticSearch a lot, but as a document store, not that much for logs and performance monitoring.

You probably want to use an external container for ElasticSearch and another one for LogStash.

The instructions of the official ElasticSearch Docker image are here: https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html

They come with a trial version of X-Pack, their commercial private software. But it seems they now provide an alternative image with only the open source part under the name of `oss` (before you had to disable it with environment variables).

---

If you want a kind of guide on how to set up a multi-container project like that, you might want to check: https://github.com/tiangolo/full-stack (although it doesn't come with ElasticSearch).

Good luck!

**Comment by tiangolo** [comment]
Given the lack of additional comments in some time, I'll assume you solved your problem and close this issue. But feel free to post more comments here if you want to re-open it or continue the conversation.
