### ISSUE TITLE
Cannot find Python module with Conda

### ISSUE THREAD

**Issue by TamanKaax** [tiangolo/uwsgi-nginx-flask-docker#53]
Hi,
First of all, thanks for the great work!
I adapted the image by installing conda on top of it. I need conda to install the fast.ai library and all its dependencies. I do this on the base conda env.

When i try to run the container, it cannot find the fastai library.
However, when i run the container interactively, it runs the flask app without any issues. hence the Flask development webserver can find the fastai library but nginx/uwsgi/supervisor cannot.

Any idea how to solve this issue? What files / settings need to be adapted?

Thanks!
Francis

**Comment by tiangolo** [comment]
I think you are probably having 2 Python environments. One that comes with this image and one with conda that you use to install fast.ai. 

I think you could try installing `uwsgi` with conda, or at least with the `pip` in your conda installation, and then modify the [`supervisord.conf`](https://github.com/tiangolo/uwsgi-nginx-docker/blob/master/python3.6/supervisord.conf#L5) to use the path of the new `uwsgi` from your conda environment.

**Comment by cameroncruz** [comment]
I encountered a similar issue and had to create a modified supervisord.conf as per @tiangolo 's reply. For future readers, this repo shows how to properly use miniconda on top of uwsgi-nginx-flask:python3.6 without environment conflicts: https://github.com/cameroncruz/flask-nginx-uwsgi-miniconda

**Comment by KingDarBoja** [comment]
> I encountered a similar issue and had to create a modified supervisord.conf as per @tiangolo 's reply. For future readers, this repo shows how to properly use miniconda on top of uwsgi-nginx-flask:python3.6 without environment conflicts: https://github.com/cameroncruz/flask-nginx-uwsgi-miniconda

Just to point out, the following command is deprecated on latest version of miniconda3 (using 4.7.12.1):
`conda build purge-all`

The warning prompt suggest:
`conda build purge-all`

Cheers!

**Comment by tiangolo** [comment]
Thanks for the note @KingDarBoja !

**Comment by KingDarBoja** [comment]
I just noticed the warning prompt was the same as the deprecation notice, I think it should be `conda build purge` but can't remember right now.

Anyway, glad to help 🚀

**Comment by tiangolo** [comment]
Great!

@TamanKaax if your question is solved, you can close the issue.
