### ISSUE TITLE
COPY failed on step 9

### ISSUE THREAD

**Issue by HarperKoo** [tiangolo/uwsgi-nginx-flask-docker#54]
When I use https://github.com/tiangolo/uwsgi-nginx-flask-docker/blob/master/python3.6/Dockerfile

It raise 
Step 9/17 : COPY ./app /app
COPY failed: stat /var/lib/docker/tmp/docker-builder416121774/app: no such file or directory

**Comment by tiangolo** [comment]
Has it happened more than once?

**Comment by tiangolo** [comment]
Given the lack of additional comments in some time, I'll assume you solved your problem and close this issue. But feel free to post more comments here if you want to re-open it or continue the conversation.
