### ISSUE TITLE
Would I be able to use any flask app, just making sure I have the main.py and everything in the app directory?

### ISSUE THREAD

**Issue by guppythegod** [tiangolo/uwsgi-nginx-flask-docker#55]
Or is there something different if I have static content (js, css, img) and templates (html)

**Comment by tiangolo** [comment]
Make sure you put `static/` and `templates/` inside the container in `/app/` and it should work.

You can follow the Flask getting started tutorial, read this project's "General Instructions" (one paragraph): https://github.com/tiangolo/uwsgi-nginx-flask-docker#general-instructions and you can try one of the example projects that have everything set up, you can download and try for yourself right away: https://github.com/tiangolo/uwsgi-nginx-flask-docker#examples-project-templates

**Comment by guppythegod** [comment]
@tiangolo thank you for clearing that up!
