### ISSUE TITLE
What is the last line in the Dockerfile

### ISSUE THREAD

**Issue by guppythegod** [tiangolo/uwsgi-nginx-flask-docker#57]
Im a little confused on whether the last line in my dockerfil be this:
```
CMD ["python", "main.py"]
```
Or should it be something else?

**Comment by ronlut** [comment]
You shouldn't have a line starting your app.
The CMD (or the ENTRYPOINT if you run your container with a custom command) of the base image takes care of that, just copy your app (having a main.py) to /app and it will start automatically.

**Comment by guppythegod** [comment]
Thanks for clearing that up!

**Comment by tiangolo** [comment]
Thanks @ronlut for helping here! :+1: :cake:
