### ISSUE TITLE
Permission denied for uwsgi.sock

### ISSUE THREAD

**Issue by deeagle001** [tiangolo/uwsgi-nginx-flask-docker#58]
Hello,

I appreciate your great work putting this container altogether.

I used your container, and it was working on my ubuntu machine, but not in the other, and I am not 100% sure the problem is on my side.
Maybe you have more experience to find the root cause.

Whenever I try to access to access the page, I got permission denied issue for the uwsgi.sock file.

```
2018/05/11 10:51:27 [alert] 12#12: *1 readv() failed (13: Permission denied) while reading upstream, client: IP, server: , request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///tmp/uwsgi.sock:", host: "URL"
```

I searched for this error and there was two solutions they found.
One is to change the permission for sock to 666 and the other one is to disable SELinux.
I tried both but no luck.

I tried another nginx+uwsgi docker container created for Django from another author, and it works like charm. This means the docker is fine. They were not running parallel, just used for test.

Do you have any idea, what can cause the problem?

**Comment by tiangolo** [comment]
You can create a public repo reproducing the error, or show me the contents of each file here (but I think it's easier to create a repo), and with that, I can take a look at it and see if I can find the issue.

**Comment by deeagle001** [comment]
Later, we figured out the problem was with the host machine.
I still do not know the real root cause.
We easily migrated to another machine exact the same container and worked like charm.

So I close this ticket now.

**Comment by tiangolo** [comment]
Ok, cool. Thanks for reporting back and closing the issue. :+1:
