### ISSUE TITLE
Raspberry pi: standard_init_linux.go:190: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by crawforc3** [tiangolo/uwsgi-nginx-flask-docker#67]
What do I need to do to get the python3.6 container running on a Raspberrypi 3?

```
> docker run -it tiangolo/uwsgi-nginx-flask:python3.6 bash -il
standard_init_linux.go:190: exec user process caused "exec format error" 
```

**Comment by tiangolo** [comment]
Oh! Right, sorry, I get what happened.

This image, `tiangolo/uwsgi-nginx-flask` is based on another one more generic, not customized for Flask, [`tiangolo/uwsgi-nginx`](https://github.com/tiangolo/uwsgi-nginx-docker).

That one ( `uwsgi-nginx` ) is actually based on the official Python 3.6 image (which has a version for Pis), so building that should actually work on a Pi:

```
git clone https://github.com/tiangolo/uwsgi-nginx-docker.git
cd uwsgi-nginx-docker/python3.6
docker build -t tiangolo/uwsgi-nginx:python3.6 .
```

After building `uwsgi-nginx`, you should be able to go again and build `uwsgi-nginx-flask`, as it is based on `uwsgi-nginx`, which you will already have locally as you just built it.

```
cd ../../uwsgi-nginx-flask-docker/python3.6
docker build -t tiangolo/uwsgi-nginx-flask:python3.6 .
```

**Comment by crawforc3** [comment]
Thanks for the help! That solves it!

Just for posterity, these are the commands I ran from start to finish for a working build

```
# Clone and build image that has rpi support

git clone https://github.com/tiangolo/uwsgi-nginx-docker.git
cd uwsgi-nginx-docker/python3.6
docker build -t tiangolo/uwsgi-nginx:python3.6 .

cd ../../

# Clone and build image that is customized for Flask (uses the previous image as the base)

git clone https://github.com/tiangolo/uwsgi-nginx-flask-docker.git
cd uwsgi-nginx-flask-docker/python3.6
docker build -t tiangolo/uwsgi-nginx-flask:python3.6 .

# Run the image 
docker run -it tiangolo/uwsgi-nginx-flask:python3.6 bash

```

**Comment by tiangolo** [comment]
Thanks for reporting back! :tada:

**Comment by crawforc3** [comment]
@tiangolo Do you have any thoughts on how I could package all of this into one Dockerfile?

**Comment by tiangolo** [comment]
Do you mean a single `Dockerfile` with everything? 

If that's the case, I guess that you don't want to have to be building 3 images in each Raspberry Pi for your image to work or something similar. Also, have in mind that once the 2 base images are built on your Pi, you don't have to re-build them again, the images persist in your Docker, inside your Pi. You only need to rebuild your app image.

But if you want to deploy it to several Pis I guess you wouldn't want to compile 3 images each time.

If you are running it on a Raspberry Pi, I imagine it probably won't serve a large scale user base. If that's the case, you could just install uWSGI, without Nginx, and use it directly. Recent versions of uWSGI are supposed to have decent performance without absolutely requiring Nginx. And by discarding Nginx, you no longer need to have 2 processes at the same time, so you no longer need to have a third process to control the other 2 (Supervisord). So you could discard that too. In summary, I think you can try with uWSGI alone and see how it goes. It should be way simpler to set up.

**Comment by crawforc3** [comment]
I suppose, there's no real reason for me to put this on multiple Raspberry Pi's, but sometimes we do things for fun :) 

Regardless, I ended up building each base image on a Raspberry Pi and pushing them to dockerhub. This allows me to mirror the way you've setup your Dockerimages and I can pull the two base images, however now they have been built specifically for a Raspberry Pi.

https://hub.docker.com/r/crawforc3/raspberrypi-uwsgi-nginx/
https://hub.docker.com/r/crawforc3/raspberrypi-uwsgi-nginx-flask/

**Comment by tiangolo** [comment]
Ah! Cool! :whale:

**Comment by rodrigorodrigues** [comment]
Hi @crawforc3 ,

Would you mind please share your repo for the raspberry pi image you created?

I'm trying to build a multi platform image using Github Action + buildx but the arm64 is not working showing "exec format error".

I'm using `tiangolo/uwsgi-nginx-flask:python3.8`.

Thanks

**Comment by guysoft** [comment]
I crated a github action that builds arm64 and armf on all containers.For now its pushed to my repo:
https://github.com/tiangolo/uwsgi-nginx-docker/issues/87#issuecomment-899106224
