### ISSUE TITLE
Static folder not working

### ISSUE THREAD

**Issue by clearproof** [tiangolo/uwsgi-nginx-flask-docker#68]
Im using flask bootstrap and need to serve the bootstrap files locally but Im getting a 404 when it tries to get the bootstrap files. Also my static folder is not working. Is it because of the project structre ? How should the project structure be with a static folder ? Thanks

**Comment by tiangolo** [comment]
Checkout this example: https://github.com/tiangolo/uwsgi-nginx-flask-docker/tree/master/example-flask-python3.6-index

Put your static files inside `./static` and make sure your links to them go to `/static/some-static-file.css`.

**Comment by tiangolo** [comment]
Given the lack of additional comments in some time, I'll assume you solved your problem and close this issue. But feel free to post more comments here if you want to re-open it or continue the conversation.
