### ISSUE TITLE
link in your docs doesn't work

### ISSUE THREAD

**Issue by tommyjcarpenter** [tiangolo/uwsgi-nginx-flask-docker#69]
this is a 404: http://nichol.as/benchmark-of-python-web-servers

it is referenced from here: https://hub.docker.com/r/tiangolo/uwsgi-nginx-flask/

**Comment by tiangolo** [comment]
Sorry for the delay, I was busy building [**FastAPI**](https://github.com/tiangolo/fastapi).

I just updated the README with recent third-party benchmarks and links to new alternative images (with better performance).

I'll close this issue, but feel free to re-open it, add comments or add new issues.
