### ISSUE TITLE
Changing uwsgi block size

### ISSUE THREAD

**Issue by rodrigoSantamaria** [tiangolo/uwsgi-nginx-flask-docker#72]
Hi there,
I'm trying to change the block size (default 4096) cause of the nature of my server I need some very long requests (~8K), and tiangolo-uwskgi-nginx reports:
`invalid request block size: 6168 (max 4096)...skip`

So I tried to add to the startup.sh some lines like this:
    location @app {
        include uwsgi_params;
        uwsgi_pass unix:///tmp/uwsgi.sock;
    	uwsgi_buffers           2 16k;
    	uwsgi_buffer_size	16k;
    	uwsgi_busy_buffers_size 16k;
    }
But to no avail, the block size is still 4096. Maybe it's a Nginx question more than related to this docker container, but I'm afraid the container is somehow interfering?

Cheers!

**Comment by tiangolo** [comment]
In a more or less "recent" update I made the Nginx default have unlimited file upload sizes, as would be the default for a Flask app.

But previously it had the Nginx default (1 MB or something like that). Please make sure you have the latest image first:

```bash
docker pull tiangolo/uwsgi-nginx-flask:python3.6
```

---

If the problem persists, you can create a public repo showing the error, that way I can check it and help you fix it.

**Comment by tiangolo** [comment]
@TodimuJ you might want to check this answer: https://stackoverflow.com/a/26941287/219530

Linking to this section in uWSGI's docs: https://uwsgi-docs.readthedocs.io/en/latest/ThingsToKnow.html

It seems you may need to adjust the `buffer-size` config.

Then you can probably set it with environment variables: https://uwsgi-docs.readthedocs.io/en/latest/Configuration.html#environment-variables

E.g.

```
UWSGI_BUFFER_SIZE=32768
```

**Comment by TodimuJ** [comment]
Hey, thanks for the comment. I did try to put the following command in my Dockerfile and didn't seem to solve the issue:

ENV UWSGI_BUFFER_SIZE=32768

Or am I setting this wrongly?

Thanks.

**Comment by TodimuJ** [comment]
> Hey, thanks for the comment. I did try to put the following command in my Dockerfile and didn't seem to solve the issue:
> 
> ENV UWSGI_BUFFER_SIZE=32768
> 
> Or am I setting this wrongly?
> 
> Thanks.

I also checked the logs of my application. It does state that the buffer-size has been changed to 32768 but it also states that my memory page size is 4096 bytes.

**Comment by tiangolo** [comment]
Hey @TodimuJ if you're still having problems, please create a new issue with a minimal self-contained example, that way it's easier to track it and see what's happening.
