### ISSUE TITLE
Response 403 from REST API

### ISSUE THREAD

**Issue by khannajai** [tiangolo/uwsgi-nginx-flask-docker#74]
I am querying the JIRA REST API and an Influx DB from my flask app and displaying some data on a dashboard. When I run the flask app on my machine (without docker), everything looks fine. I am able to query the API and InfluxDB and show the metrics.

When I run my app in the docker container and then view it on localhost:80, I am able to see the layout of my dashboard, but my queries to the database and the REST API fail with HTTP response 403. Pip is able to correctly install packages in the container, so there is internet access.

What could be the problem?

**Comment by khannajai** [comment]
I set --net=host when running the container, and then the queries worked. Is there perhaps a better solution that doesn't map all docker ports to the host?

**Comment by tiangolo** [comment]
I don't really know what was causing your problem, to have more information it would be useful to check the Docker logs of your container, check the logs in your Developer Tools console (in your browser).

Also, some more information would be useful, is your InfluxDB another container in the same Docker Compose stack? Is it directly in the host? In another host? What errors do you see in your logs? Who is complaining, JIRA or your InfluxDB?
