### ISSUE TITLE
Avoid running RUN command as muchas possible

### ISSUE THREAD

**Issue by Guilhermeslucas** [tiangolo/uwsgi-nginx-flask-docker#76]
Hi! Really greate work with the Dockerfiles, congatulations! I was looking at some code and saw that we can enhance it avoiding to use RUN as much as possible, like this [link](https://docs.docker.com/v17.09/engine/userguide/eng-image/dockerfile_best-practices/#avoid-installing-unnecessary-packages) says. Do you want some help with this?
Thanks a lot!

**Comment by tiangolo** [comment]
Thanks!

I see the link says "Avoid installing unnecessary packages", and below it says "Minimize the number of layers", but not really to avoid `RUN` as much as possible.

Nevertheless, I see only 3 `RUN` instructions, doing different things, so it wouldn't make sense to put them together.

But do you think there is any other section that should be optimized? Which and how?

And thanks for offering help!

**Comment by Guilhermeslucas** [comment]
I was looking at it and you are totally right. Closing it!

**Comment by tiangolo** [comment]
Ok, cool! Thanks for reporting back and closing it.
