### ISSUE TITLE
where is my log file in flask

### ISSUE THREAD

**Issue by zhiqiu** [tiangolo/uwsgi-nginx-flask-docker#80]
I use logging to write logfile, where is it in container?

**Comment by tiangolo** [comment]
It redirects the logs to "standard output" like many standard Docker images.

You can see the combined logs (Nginx, Supervisord and uWSGI) with something like:

```bash
docker logs my-super-container
```

**Comment by zhiqiu** [comment]
@tiangolo thanks. Is there any "max size" restriction for the logs?

**Comment by tiangolo** [comment]
As it is just redirected to "standard output", it's not handled by the programs inside the container but by Docker directly. It is not necessarily stored in a file of a certain size, but it actually depends on the configurations of Docker itself. There are even "logging drivers" for more advanced use cases.

Check the Docker docs for `docker logs`: https://docs.docker.com/engine/reference/commandline/logs/

**Comment by tiangolo** [comment]
I assume you were able to solve your problem, so I'll close this issue now.

But feel free to re-open, add more comments or create new issues.

**Comment by johnbfox** [comment]
If you manually create a log handler in your Flask app, does the output automatically get routed to stdout?  I have a WatchedFileHandler that I'm attempting to use so that I can log to mounted volume.  The log file gets created but none of the logging seems to get recorded.  Just trying to make sure that this is because of the container and not an improper app configuration.

**Comment by tiangolo** [comment]
Sorry for the delay @johnbfox . In theory, if you override the log to do something else and write logs somewhere else, they should go to where you say.

For linux, `stdout` is treated more or less like a "file". So, if you override the logs and write to another file, it *should* write those logs there in the other file.
