### ISSUE TITLE
why including a nginx in the same container?

### ISSUE THREAD

**Issue by orctom** [tiangolo/uwsgi-nginx-flask-docker#84]
I see people put Nginx into a separate container, and have them working together by such as docker-compose.

We are putting Nginx in the same image, there must be some reason. What are they?

**Comment by tiangolo** [comment]
Here are the technical details: https://github.com/tiangolo/uwsgi-nginx-flask-docker#technical-details

**Comment by tiangolo** [comment]
I assume this solved your doubt and/or you were able to continue with your project, so I'll close this issue now.

But feel free to re-open, add more comments or create new issues.
