### ISSUE TITLE
WebSockets support?

### ISSUE THREAD

**Issue by danmysak** [tiangolo/uwsgi-nginx-flask-docker#85]
Is there a way to use WebSockets with `tiangolo/uwsgi-nginx-flask`?

[Here](https://github.com/miguelgrinberg/Flask-SocketIO/issues/798#issuecomment-423852377) is the reply I got from the developer of Flask-SocketIO, but I can’t quite figure out what exactly I’m supposed to do here. Thanks.

**Comment by tiangolo** [comment]
Good question.

Here's the thing. Flask was made before there was first class asynchronous support in Python (Python 2.x). To be able to use asynchronous code in Python 2.x it was necessary to use Gevent or similar tools. It monkeypatches Python itself (modifies its internals) and provides an interface similar to threads, which I find quite more cumbersome than the more recent async features of Python 3.x, with `async` and `await`. Don't get me wrong, it was great for the time it was built. I just prefer the new Python constructs when it's possible.

Flask-SocketIO depends on Gevent (or Eventlet). So, a server that runs on top of those is necessary.

Reading his docs, I see that it would probably be possible to integrate it with this image by making uWSGI run with Gevent and adding the WebSocket endpoints in Nginx. Both of those options are documented in his docs.

---

But now, Flask-SocketIO claims to have a production ready server. I think you could try using that directly. It might probably make more sense for your project.

And that way you woudn't have to deal with handling all the independent components that come with this image (uWSGI, Nginx, handled by Supervisord, and then adding Gevent, and debug that it's working properly, etc).

For example, a `main.py` with something like:

```python
from flask import Flask, render_template
from flask_socketio import SocketIO

app = Flask(__name__)
app.config['SECRET_KEY'] = 'secret!'
socketio = SocketIO(app)

if __name__ == '__main__':
    socketio.run(app)
```

and a `Dockerfile` with:

```Dockerfile
FROM python:3.7

RUN pip install gevent flask flask-socketio

COPY ./ /app

EXPOSE 80

RUN python main.py
```

Just that might actually work for your purposes.

**Comment by danmysak** [comment]
Thank you, Sebastián. I’ll try this out.

**Comment by danmysak** [comment]
Unfortunately, I still can’t get it to work. However, since the easier (potential) solution is about Flask-SocketIO and not about uwsgi-nginx-flask, I think it would be appropriate if I close the issue. Thank you for your help.

**Comment by tiangolo** [comment]
Hey @danmysak , just to let you know that I created https://github.com/tiangolo/fastapi.

It has a lot of inspiration from Flask and many others, with several benefits while building APIs.

It has direct support for WebSockets: https://fastapi.tiangolo.com/tutorial/websockets/ among many other features.

There are official Docker images, project generators, etc.

**Comment by milanashik** [comment]
Hey, did anyone figure how to use use WebSockets with tiangolo/uwsgi-nginx-flask?
