### ISSUE TITLE
Advice for analytics platforms?

### ISSUE THREAD

**Issue by alexshadley** [tiangolo/uwsgi-nginx-flask-docker#87]
I'm looking at setting up an analytics platform like Piwik alongside nginx in the container, but it's trickier than I'd hoped.  Any advice for which platform might be easiest to set up with this system, and where I should start?  Thanks!

**Comment by tiangolo** [comment]
I'm not familiar with Piwik (now it seems to be called Matomo). Many tech products use the term "analytics" as if it was very specific and related to their product, but they use it in many different contexts. But I guess it's like a sort of Google Analytics, right? 

Do you want to measure frontend page hits? API endpoints usage?

**Comment by alexshadley** [comment]
That's the idea!  I'm mostly after analyzing API endpoint usage, so I suppose I could write my own analytics module as part of the flask app.  I just thought I'd look into options at the webserver level, since it would be nice to use an existing project.

**Comment by tiangolo** [comment]
I haven't explored that very much. I would probably try connecting it with ElasticSearch combined with Logstash. Or if you want Matomo, maybe with this package: https://github.com/matomo-org/piwik-python-api

**Comment by tiangolo** [comment]
I assume you were able to solve your problem, so I'll close this issue now.

But feel free to re-open, add more comments or create new issues.

---

Also, I recently created [**FastAPI**](https://github.com/tiangolo/fastapi). It has a dependency injection system that you could use to collect statistics about each endpoint (among many other things) in a very simple and reusable way. You might want to check it out.
