### ISSUE TITLE
Image python3.7-alpine3.7 dependency error

### ISSUE THREAD

**Issue by bandaangosta** [tiangolo/uwsgi-nginx-flask-docker#89]
Hi, Sebastián. Thanks for your great work!

I have an issue when using your latest alpine image `tiangolo/uwsgi-nginx-flask:python3.7-alpine3.7` as base for a web app that uses Pandas (and therefore Numpy as dependency).
When I start the container I get the following:

```
Checking for script in /app/prestart.sh
Running script /app/prestart.sh
Running inside /app/prestart.sh, you could add migrations to this file, e.g.:

#! /usr/bin/env bash

# Let the DB start
sleep 10;
# Run migrations
alembic upgrade head

/usr/lib/python2.7/site-packages/supervisor/options.py:298: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  'Supervisord is running as root and it is searching '
2018-10-04 12:49:22,989 CRIT Supervisor running as root (no user in config file)
2018-10-04 12:49:22,989 INFO Included extra file "/etc/supervisor.d/supervisord.ini" during parsing
2018-10-04 12:49:22,999 INFO RPC interface 'supervisor' initialized
2018-10-04 12:49:22,999 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2018-10-04 12:49:23,000 INFO supervisord started with pid 1
2018-10-04 12:49:24,003 INFO spawned: 'nginx' with pid 9
2018-10-04 12:49:24,007 INFO spawned: 'uwsgi' with pid 10
[uWSGI] getting INI configuration from /app/uwsgi.ini
[uWSGI] getting INI configuration from /etc/uwsgi/uwsgi.ini
*** Starting uWSGI 2.0.17 (64bit) on [Thu Oct  4 12:49:24 2018] ***
compiled with version: 6.4.0 on 27 March 2018 12:43:27
os: Linux-3.10.0-693.2.2.el7.x86_64 #1 SMP Sat Sep 9 03:55:24 EDT 2017
nodename: d6a5c0dbb8b7
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /app
detected binary path: /usr/sbin/uwsgi
your memory page size is 4096 bytes
detected max file descriptor number: 65536
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /tmp/uwsgi.sock fd 3
setgid() to 102
setuid() to 101
Python version: 3.6.5 (default, Aug 22 2018, 14:20:40)  [GCC 6.4.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x5653848aff40
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 1239640 bytes (1210 KB) for 16 cores
*** Operational MODE: preforking ***
Traceback (most recent call last):
  File "./smartcalendar/__init__.py", line 9, in <module>
    import smartcalendar.views
  File "./smartcalendar/views.py", line 8, in <module>
    from smartcalendar.lib import SmartSheet
  File "./smartcalendar/lib/SmartSheet.py", line 10, in <module>
    import pandas as pd
  File "/usr/local/lib/python3.7/site-packages/pandas/__init__.py", line 19, in <module>
    "Missing required dependencies {0}".format(missing_dependencies))
ImportError: Missing required dependencies ['numpy']
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. GAME OVER ***
2018-10-04 12:49:24,939 INFO exited: uwsgi (exit status 22; not expected)
2018-10-04 12:49:25,940 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-10-04 12:49:25,942 INFO spawned: 'uwsgi' with pid 12
...

```
However, if I start a console in the container and import pandas manually, everything works fine:

```
$ docker exec -it my_minimalflaskpandas_py37 sh
/app # python
Python 3.7.0 (default, Sep 12 2018, 02:12:15) 
[GCC 6.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas
>>> pandas.__version__
'0.23.4'
>>> import numpy
>>> numpy.__version__
'1.15.2'

```
I am no uwsgi expert (just recently switched from Apache + mod_wsgi), but I [read](https://stackoverflow.com/a/32971938) that uwsgi does not really run the Python binary, but instead uses libpython directly. In this image, uswgi, through its "Python3 plugin" is linked to Python3.6 instead of Python3.7:

```
app # ldd /usr/lib/uwsgi/python3_plugin.so 
    ldd (0x7fdad9d9b000)
    libpython3.6m.so.1.0 => /usr/lib/libpython3.6m.so.1.0 (0x7fdad96ea000)
```

This explains the `Python version: 3.6.5 (default, Aug 22 2018, 14:20:40)  [GCC 6.4.0]` line in the uwsgi start output above. And as for my particular failure, I'm guessing it comes from a mixup between installing the packages using pip (->pip3.7) and uwsgi using Python3.6:

```
/app # pip -V
pip 18.0 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)
```

So, if I'm right, you need to create this image [building uwsgi explicitly linked to Python 3.7](https://uwsgi-docs.readthedocs.io/en/latest/WSGIquickstart.html#bonus-multiple-python-versions-for-the-same-uwsgi-binary).
Please take a look. The same application works fine if using the Python3.6-based image `tiangolo/uwsgi-nginx-flask:python3.6-alpine3.7`

If you want to reproduce the issue, clone a [repo a I made for this purpose](https://github.com/bandaangosta/minimal-flask-pandas) and run:

Fails:
```
docker build -t minimalflaskpandas_37 -f Dockerfile.nginx-uwsgi.py37 .
docker run -it --rm -p 80:80 --name my_minimalflaskpandas minimalflaskpandas_37
```

Works:
```
docker build -t minimalflaskpandas_36 -f Dockerfile.nginx-uwsgi.py36 .
docker run -it --rm -p 80:80 --name my_minimalflaskpandas_36 minimalflaskpandas_36
```
The image takes around 15 or 20 minutes to build because it builds numpy and pandas.

Thanks again!

Saludos, 
José

**Comment by tiangolo** [comment]
First of all, this is one of the best issues I've received.

Excellent report with all the information, excellent previous investigation, including the logs, finding what works and what doesn't, all the info you found on the issue, links, etc.

And the full repo showing what works and what doesn't, great. Thanks for that. :clap: :clap: :clap: :cake: 

It motivated me to go and investigate the whole thing.

---

Now onto the issue:

You made me notice (and I hadn't realized) the Python 3.7 version of uWSGI (2.0.17.1) [was released in July](https://twitter.com/unbit/status/1016020324977184773?lang=en) but [the Alpine package has not been updated yet (2.0.17-r0) ](https://pkgs.alpinelinux.org/package/v3.7/main/x86/uwsgi-python3), [not even in Alpine 3.8 (2.0.17-r1) ](https://pkgs.alpinelinux.org/package/v3.8/main/x86/uwsgi-python3), the current version is just "one micro-patch" version behind, but still doesn't provide support for Python 3.7.

The Alpine package maintainer is Natanael Copa, so I just [twitted him asking about it](https://twitter.com/tiangolo/status/1048254128185593856).

As a temporary workaround, you can use Python 3.6 or the non-alpine version with Python 3.7.

I'll update here once I get more info.

¡Saludos tocayo! (Por mi primer nombre que no uso).

**Comment by bandaangosta** [comment]
Thanks for your reply! You have done an awesome job, so the least we issue creators can do is give you a hand as much as possible when asking for help. Besides, I have spent (**too**) many years creating, commenting and investigating (JIRA issue tracker) tickets in my current job. I guess it's muscle memory by now to do it thoroughly ;)

As for the issue, I can do just fine with the proposed workarounds. 

Thanks again!

¡Saludos, [José] Sebastián!

**Comment by tiangolo** [comment]
Thanks!

I just updated the `README.md` with a note about it, to prevent more people stumbling on it until there's an official uWSGI Python 3.7 package for Alpine.

**Comment by tiangolo** [comment]
I'll close this issue now as we can't do anything else until there's official support for `uwsgi` using Python 3.7 in Alpine.

---

Nevertheless, I just created a couple of alternative images with better performance (400% and 800% the performance of this image). And they support Python 3.7 on Alpine. If you still need that, you might want to check them.
