### ISSUE TITLE
running more than 2 processes

### ISSUE THREAD

**Issue by shyal** [tiangolo/uwsgi-nginx-flask-docker#9]
Hi,

Thanks for the great work. I've tried specifying the number of processes in uwsgi.ini, however it still defaults to 2. How do I spawn more than 2 processes?

Thanks.

**Comment by shyal** [comment]
Figured it out. I needed to specify processes, and also threads in the ini file. Thanks.

**Comment by tiangolo** [comment]
@shyal by default, it is configured to start with 2 processes, but to grow and shrink based on demand. So, if you have a high load, it will start more processes and if the load reduces it will kill un-needed processes until it gets to 2 again.

You can test it by creating a route and putting a `time.sleep(10)` or something like that. Then loading that same route in several tabs. Then, if you check the processes running, you'll see that they will increment automatically.

If you modify it, you might get a fixed amount of processes running all the time. That might be what you need, but the default behavior may be enough and more efficient.

**Comment by glyg** [comment]
Hi @tiangolo , thanks for your huge time saving effort!

This is somewhat related, so I'll ask here: I'd like to have only one process / worker (there will only be a single user using the app at the time), and it would make my life simpler for data management.

I tried setting that in the `uwsgi.ini` file, but it doesn't seem to change any thing:
here is the file:
```
[uwsgi]
module = main
callable = server
workers = 1
processes = 1
threads = 1
```
And the Dockerfile:
```
FROM tiangolo/uwsgi-nginx-flask:python3.6

RUN pip install --upgrade pip
COPY requirements.txt /tmp/
RUN pip install -r /tmp/requirements.txt
ENV DATA_DIR /data
ENV UWSGI_INI /app/uwsgi.ini
ENV FLASK_DEBUG=1
COPY ./app /app
```

Thanks again,

Guillaume

**Comment by glyg** [comment]
HI, I managed to have my app work with several workers, never mind the above comment, and sorry for the noise
