### ISSUE TITLE
Wrong interpreter used

### ISSUE THREAD

**Issue by ChacheGS** [tiangolo/uwsgi-nginx-flask-docker#91]
I was trying out this Dockerfile (tiangolo/uwsgi-nginx-flask:python3.7-alpine3.7) and it turns out it's running flask in python 3.6.5 instead of 3.7.0.

I changed the app to look like this and actually report the version of the interpreter:
```python
@app.route("/")
def hello():
    return "Hello World from Flask in a uWSGI Nginx Docker \
    container with Python {}".format(sys.version)
```
which results in:
![image](https://user-images.githubusercontent.com/15632523/46440999-75655680-c765-11e8-99fb-7e98eef11ddc.png)

If you run from an interactive shell in the container, `python -V` reports the expected version
![image](https://user-images.githubusercontent.com/15632523/46441114-cc6b2b80-c765-11e8-87a0-5a12e54f0e03.png)

I have tried to track where it installs the wrong version and it seems it does so when uwsgi is installed (in the parent Dockerfile)
![image](https://user-images.githubusercontent.com/15632523/46441220-23710080-c766-11e8-8ac5-e75d3f893414.png)

I guess there is a way to tell uwsgi which interpreter to use?

**Comment by tiangolo** [comment]
I'm sorry you stumbled on it.

Currently Alpine doesn't have an official Python 3.7 uWSGI package. I just updated the `README.md` here: https://github.com/tiangolo/uwsgi-nginx-flask-docker#temporarily-not-supported to mark Alpine 3.7 with Python 3.7 temporarily not supported.

For more background, check this other issue comment: https://github.com/tiangolo/uwsgi-nginx-flask-docker/issues/89#issuecomment-427437886

---

Now, meanwhile, for your specific case, there are two possible workarounds, using Alpine 3.7 with Python 3.6, or using Python 3.7, in a "standard" (Debian) image.

**Comment by tiangolo** [comment]
Sadly, we can't do anything *in this image* until there's official support for `uwsgi` running on Alpine using Python 3.7. So, I'll close this issue.

---

Nevertheless, I just created a couple of alternative images with better performance. And they support Python 3.7 on Alpine. If you still need that, you might want to check them in the updated [README](https://github.com/tiangolo/uwsgi-nginx-flask-docker).
