### ISSUE TITLE
upstream prematurely closed

### ISSUE THREAD

**Issue by federicopuntoni** [tiangolo/uwsgi-nginx-flask-docker#92]
Hi all,

I recently released an app on AWS ECS using "uwsgi-nginx-flask: python3.7"

The problem is that sporadically, without any reason, the server starts responding with "upstream prematurely closed connection while reading response".

Reading some information on the internet the cause could be due to the use of keepalive on nginx, instead of uwsgi side:

https://stackoverflow.com/a/46092301

or to use proxy_buffering:

https://github.com/owncloud/client/issues/5706#issuecomment-294433262

Has anyone encountered the same problem?

Thank you all

**Comment by tiangolo** [comment]
That's a sort of generic Nginx error that sadly doesn't say much, only that there was a problem in the connection between Nginx and uWSGI, all inside the container.

First, check the Docker logs (`docker logs mycontainer`) and see if there's any error. Also, let me suggest you [Sentry](https://sentry.io/welcome/), is amazing.

Is your endpoint doing a computationally expensive or inherently long computation?

You can try adding the `proxy_buffering` in your image directly, it's easy, check the instructions here: https://github.com/tiangolo/uwsgi-nginx-flask-docker#customizing-nginx-configurations

Please let me know anything else you discover.

**Comment by federicopuntoni** [comment]
> First, check the Docker logs (docker logs mycontainer) and see if there's any error. 

I have to wait for it to occur because it does not depend on any variable

> Also, let me suggest you Sentry, is amazing.

I'll try it

> Is your endpoint doing a computationally expensive or inherently long computation?

Absolutely not.
Also the last time occurred at night, and being a stage environment no one was connected to the app

**Comment by tiangolo** [comment]
> Also the last time occurred at night, and being a stage environment no one was connected to the app

That's quite strange :thinking: . Is your endpoint receiving a big request? Like a file upload? Or is it returning a long response? Like a big JSON or a big file?

Here are [the docs for `proxy_buffering`](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_buffering). But all the proxy buffering settings tend to have to do with buffering content that should go to your Python app from your client or to your client from your Python app. But by the docs it seems like the buffering settings would only help if there's a big payload in one of the directions.

Nevertheless, you could try adding the config and see how it changes. Is just that it would be nice to pinpoint better the actual problem.

**Comment by federicopuntoni** [comment]
> That's quite strange 🤔 . Is your endpoint receiving a big request? Like a file upload? Or is it returning a long response? Like a big JSON or a big file?

No, it's a simple bootstrap-based flask dashboard with peewee.
There are no particular features yet implemented.

**Comment by tiangolo** [comment]
Strange. Then maybe try that and let me know how it goes.

**Comment by federicopuntoni** [comment]
I understood where the problem was.

My session had a 30-day lifetime but mysql timeout was 8 hours.

Saving the database connection within the session made sure that a previously expired connection remained in session and then the exception was triggered.

Thank you

**Comment by federicopuntoni** [comment]
ok, I'll try it for sure! Thanks again

**Comment by jackadam1981** [comment]
It means closing session？
like   session.close()
