### ISSUE TITLE
Automatic Code builds - The CI in CI/CD

### ISSUE THREAD

**Issue by bttahir** [tiangolo/uwsgi-nginx-flask-docker#95]
Thank you for this project - it has helped me setup a production ready Flask app so easily! However - right now the way its setup you cannot see any changes to your code unless you kill, rebuild and re-run your Docker container? Is there a simple way to be able to see your code changes as you make them?

**Comment by bttahir** [comment]
OK - I ended up using a docker-compose file similar to your example:

`version: '3'
services:
  web:
    build: ./
    ports:
     - "8520:8520"
    volumes:
     - ./app:/app`

The bind volumes allows me to see live coding changes. I use port 8520 for weird reasons. I also updated my dockerfile to use ADD instead of COPY but not sure if it would matter either way:

`FROM tiangolo/uwsgi-nginx-flask:python3.7

ADD ./app /app

WORKDIR ./app

ENV STATIC_INDEX 1 

ENV LISTEN_PORT 8520

EXPOSE 8520
`

**Comment by tiangolo** [comment]
If you wanna check all my tricks, including development, stack structure and deployment, check this: https://github.com/tiangolo/full-stack
