### ISSUE TITLE
Python 3.6 image bundles old version of Flask and pip

### ISSUE THREAD

**Issue by strangedev** [tiangolo/uwsgi-nginx-flask-docker#96]
The image currently bundles Flask version 0.12.2 and pip version 9.03.
Currently (2018-10-18), the latest stable versions of both are pip version 18.1 and Flask version 1.0.2.

**Comment by strangedev** [comment]
Could be a problem with caching of images in my deployment, hang on...

**Comment by strangedev** [comment]
Turned out to be exactly that. Apologies for creating an issue without proper testing.

**Comment by tiangolo** [comment]
Hehe, I'm glad you solved it. Thanks for reporting back and closing the issue :+1:
